ActivityType.create!([
  {activity_id: 1, atype_old: "image", value: {"description"=>"Take a selfie with the stone and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 4, atype_old: "image", value: {"description"=>"Take a selfie with the stone and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 5, atype_old: "image", value: {"description"=>"Take a selfie with the stone and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 7, atype_old: "image", value: {"description"=>"Take a Selfie and post it to the feed"}, deleted: false, atype: "image"},
  {activity_id: 9, atype_old: "image", value: {"description"=>"Take a selfie taking a free spin and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 8, atype_old: "image", value: {"description"=>"Take a selfie rubbing Buddha's Belly and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 10, atype_old: "image", value: {"description"=>"Take a selfie with the stone and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 11, atype_old: "image", value: {"description"=>"Take a selfie taking a free spin and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 12, atype_old: "image", value: {"description"=>"Image Required"}, deleted: false, atype: "image"},
  {activity_id: 14, atype_old: "post", value: {"description"=>"Post Required"}, deleted: false, atype: "post"},
  {activity_id: 16, atype_old: "image", value: {"description"=>"Image Required"}, deleted: false, atype: "image"},
  {activity_id: 17, atype_old: "image", value: {"description"=>"Take a selfie with Vegas Vic and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 18, atype_old: "activity_code", value: {"id"=>"1234", "description"=>"Visit the guard at the pool entrance to receive code."}, deleted: false, atype: "activity_code"},
  {activity_id: 19, atype_old: "image", value: {"description"=>"Take a selfie with the stone and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 20, atype_old: "image", value: {"description"=>"Take a Selfie and post it to the feed"}, deleted: false, atype: "image"},
  {activity_id: 21, atype_old: "activity_code", value: {"id"=>"1234", "description"=>"Code: 1234"}, deleted: false, atype: "activity_code"},
  {activity_id: 22, atype_old: "image", value: {"description"=>"Take a selfie with the Binion’s million and post it to the feed"}, deleted: false, atype: "image"},
  {activity_id: 23, atype_old: "image", value: {"description"=>"Take a picture of the sign and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 24, atype_old: "image", value: {"description"=>"Take a selfie walking across Abbey Road and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 26, atype_old: "image", value: {"description"=>"Take a selfie taking a free spin and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 27, atype_old: "image", value: {"description"=>"Take a selfie rubbing Buddha's Belly and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 31, atype_old: nil, value: {"id"=>"12345", "description"=>"12345"}, deleted: false, atype: "activity_code"},
  {activity_id: 6, atype_old: "beacon", value: "{\"id\"=>\"1234\"}", deleted: false, atype: "activity_code"},
  {activity_id: 5, atype_old: "beacon", value: "{\"id\"=>\"1234\"}", deleted: false, atype: "activity_code"},
  {activity_id: 4, atype_old: "beacon", value: "{\"id\"=>\"1234\"}", deleted: false, atype: "activity_code"},
  {activity_id: 33, atype_old: nil, value: {"description"=>"Take a photo with the human statue and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 37, atype_old: nil, value: {"description"=>"Take a selfie over the balcony and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 35, atype_old: nil, value: {"description"=>"Take a picture of the statue and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 39, atype_old: nil, value: {"description"=>"Take a selfie with the waterfall and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 38, atype_old: nil, value: {"description"=>"Get creative, take your best picture of the exhibit and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 19, atype_old: "beacon", value: {"id"=>"1"}, deleted: false, atype: "beacon"},
  {activity_id: 36, atype_old: nil, value: {"id"=>"1234", "description"=>"Code: 1234"}, deleted: false, atype: "activity_code"},
  {activity_id: 15, atype_old: "beacon", value: "{\"id\"=>\"1234\"}", deleted: false, atype: "activity_code"},
  {activity_id: 1, atype_old: "beacon", value: "{\"id\"=>\"1234\"}", deleted: false, atype: "activity_code"},
  {activity_id: 42, atype_old: nil, value: {"description"=>"whatever"}, deleted: false, atype: "post"},
  {activity_id: 13, atype_old: "beacon", value: "{\"id\"=>\"1234\"}", deleted: false, atype: "activity_code"},
  {activity_id: 10, atype_old: "beacon", value: "{\"id\"=>\"1234\"}", deleted: false, atype: "activity_code"},
  {activity_id: 8, atype_old: "beacon", value: "{\"id\"=>\"1234\"}", deleted: false, atype: "activity_code"},
  {activity_id: 7, atype_old: "beacon", value: "{\"id\"=>\"1234\"}", deleted: false, atype: "activity_code"},
  {activity_id: 20, atype_old: "beacon", value: {"id"=>"1"}, deleted: false, atype: "beacon"},
  {activity_id: 25, atype_old: "beacon", value: {"id"=>"1"}, deleted: false, atype: "beacon"},
  {activity_id: 27, atype_old: "beacon", value: {"id"=>"1"}, deleted: false, atype: "beacon"},
  {activity_id: 27, atype_old: nil, value: {"id"=>"1"}, deleted: false, atype: "beacon"},
  {activity_id: 32, atype_old: nil, value: {"description"=>"Take a selfie and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 43, atype_old: nil, value: {"description"=>"Take a photo of the chapel and post it to your quest."}, deleted: false, atype: "image"},
  {activity_id: 40, atype_old: nil, value: {"description"=>"make a post"}, deleted: false, atype: "post"},
  {activity_id: 41, atype_old: nil, value: {"description"=>"post an image "}, deleted: false, atype: "image"},
  {activity_id: 32, atype_old: nil, value: {"id"=>"1"}, deleted: true, atype: "beacon"},
  {activity_id: 39, atype_old: nil, value: {"id"=>"1"}, deleted: true, atype: "beacon"},
  {activity_id: 44, atype_old: nil, value: {"id"=>"Viva", "description"=>"Fill in the blank: “____ Las Vegas Wedding Chapel” "}, deleted: false, atype: "activity_code"},
  {activity_id: 45, atype_old: nil, value: {"id"=>"Collins", "description"=>"There is a sign on property to make sure the world knows! \r\nFill in the Blank: “Joan _____ & Michael Jordan were married here.” "}, deleted: false, atype: "activity_code"},
  {activity_id: 34, atype_old: nil, value: {"id"=>"1234", "description"=>"Code: 1234"}, deleted: false, atype: "activity_code"},
  {activity_id: 46, atype_old: nil, value: {"id"=>"Legendary", "description"=>"This phrase is shown somewhere on the marquee.\r\nFill in the blank: “Intimate - Elegant - _______”"}, deleted: false, atype: "activity_code"},
  {activity_id: 47, atype_old: nil, value: {"description"=>"Channel your inner wedding photographer! Eye a romantic moment and take a photo."}, deleted: false, atype: "image"},
  {activity_id: 48, atype_old: nil, value: {"description"=>"Take a selfie in front of the water fountain."}, deleted: false, atype: "image"},
  {activity_id: 50, atype_old: nil, value: {"description"=>"Take a photo in front of the iconic sign."}, deleted: false, atype: "image"},
  {activity_id: 49, atype_old: nil, value: {"id"=>"7"}, deleted: false, atype: "beacon"},
  {activity_id: 55, atype_old: nil, value: {"description"=>"Choose a statue that suits your fancy and snap a photo of someone mimicking or posing with it."}, deleted: false, atype: "image"},
  {activity_id: 63, atype_old: nil, value: {"description"=>"Take an up close photo of a green monster."}, deleted: false, atype: "image"},
  {activity_id: 66, atype_old: nil, value: {"id"=>"z", "description"=>"What letter is depicted on this 3D mural? "}, deleted: false, atype: "activity_code"},
  {activity_id: 70, atype_old: nil, value: {"description"=>"Post your opinion about this piece."}, deleted: false, atype: "post"},
  {activity_id: 67, atype_old: nil, value: {"id"=>"3", "description"=>"How many eagles are within this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 62, atype_old: nil, value: {"id"=>"2", "description"=>"How many semi trucks make up this sculpture?"}, deleted: false, atype: "activity_code"},
  {activity_id: 65, atype_old: nil, value: {"description"=>"Take a peak inside the Art Motel and snap a photo."}, deleted: false, atype: "image"},
  {activity_id: 68, atype_old: nil, value: {"id"=>"linus", "description"=>"What character from the cartoon Peanuts is this mural based off?"}, deleted: false, atype: "activity_code"},
  {activity_id: 51, atype_old: nil, value: {"id"=>"Las Vegas Aces", "description"=>"What team jersey is Lady Liberty wearing?"}, deleted: false, atype: "activity_code"},
  {activity_id: 52, atype_old: nil, value: {"description"=>"Take a photo of Leo the Lion."}, deleted: false, atype: "image"},
  {activity_id: 53, atype_old: nil, value: {"description"=>"Post a photo of the Eiffel Tower replica."}, deleted: false, atype: "image"},
  {activity_id: 56, atype_old: nil, value: {"description"=>"Snap a photo of the world record breaking observation wheel."}, deleted: false, atype: "image"},
  {activity_id: 57, atype_old: nil, value: {"description"=>"Take a photo of a gondola."}, deleted: false, atype: "image"},
  {activity_id: 58, atype_old: nil, value: {"description"=>"Strike a pose in front of this fascinating building."}, deleted: false, atype: "image"},
  {activity_id: 61, atype_old: nil, value: {"id"=>"3", "description"=>"How many Yerman monsters are depicted in this mural? "}, deleted: true, atype: "activity_code"},
  {activity_id: 60, atype_old: nil, value: {"id"=>"11"}, deleted: false, atype: "beacon"},
  {activity_id: 54, atype_old: nil, value: {"description"=>"Post a photo of the fountains in action.\r\n*you may have to wait a few minutes; the fountain show occurs every half hour"}, deleted: false, atype: "post"},
  {activity_id: 59, atype_old: nil, value: {"description"=>"Look up and snap a photo of the light show. "}, deleted: false, atype: "image"},
  {activity_id: 64, atype_old: nil, value: {"description"=>"Pose for a picture, meerkat-style. Try to mimic the meerkats so you look like you belong!"}, deleted: false, atype: "image"},
  {activity_id: 69, atype_old: nil, value: {"id"=>"heart", "description"=>"Fill in the blank: \"I gave her my _____, and she gave me…\""}, deleted: false, atype: "activity_code"},
  {activity_id: 61, atype_old: nil, value: {"id"=>"4"}, deleted: false, atype: "beacon"},
  {activity_id: 65, atype_old: nil, value: {"id"=>"5"}, deleted: false, atype: "beacon"},
  {activity_id: 73, atype_old: nil, value: {"id"=>"blood", "description"=>"What is shooting out of the toad's eye?"}, deleted: false, atype: "activity_code"},
  {activity_id: 74, atype_old: nil, value: {"id"=>"6"}, deleted: true, atype: "beacon"},
  {activity_id: 75, atype_old: nil, value: {"description"=>"Take a silly face selfie with one of the monsters."}, deleted: false, atype: "image"},
  {activity_id: 72, atype_old: nil, value: {"id"=>"7", "description"=>"What number is depicted on the robot's slot machine?"}, deleted: false, atype: "activity_code"},
  {activity_id: 77, atype_old: nil, value: {"id"=>"3", "description"=>"How many eagles are depicted in this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 79, atype_old: nil, value: {"id"=>"heart", "description"=>"Fill in the blank: \"I gave her my _____, but she left me for...\""}, deleted: false, atype: "activity_code"},
  {activity_id: 71, atype_old: nil, value: {"description"=>"Take a \"kool\" selfie with this mural."}, deleted: false, atype: "image"},
  {activity_id: 80, atype_old: nil, value: {"id"=>"100", "description"=>"What is the value of the poker chips depicted in this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 81, atype_old: nil, value: {"id"=>"3", "description"=>"How many birds are depicted in the skull of this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 82, atype_old: nil, value: {"id"=>"maker", "description"=>"Fill in the blank: \"Be a _____!\""}, deleted: false, atype: "activity_code"},
  {activity_id: 85, atype_old: nil, value: {"id"=>"Johnny Depp", "description"=>"Who stars in the movie this mural is based of?"}, deleted: false, atype: "activity_code"},
  {activity_id: 86, atype_old: nil, value: {"id"=>"6"}, deleted: false, atype: "beacon"},
  {activity_id: 86, atype_old: nil, value: {"description"=>"Take a selfie with the swan."}, deleted: false, atype: "image"},
  {activity_id: 87, atype_old: nil, value: {"description"=>"Take a photo of the rooster"}, deleted: false, atype: "image"},
  {activity_id: 88, atype_old: nil, value: {"id"=>"3", "description"=>"How many eagles are depicted in this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 90, atype_old: nil, value: {"id"=>"heart", "description"=>"Fill in the blank: \"I gave her my _____, but she left me for...\""}, deleted: false, atype: "activity_code"},
  {activity_id: 91, atype_old: nil, value: {"id"=>"100", "description"=>"What is the value of the poker chips depicted in this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 92, atype_old: nil, value: {"id"=>"3", "description"=>"How many birds are depicted in the skull of this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 94, atype_old: nil, value: {"id"=>"maker", "description"=>"Fill in the blank: \"Be a _____!\""}, deleted: false, atype: "activity_code"},
  {activity_id: 96, atype_old: nil, value: {"id"=>"Johnny Depp", "description"=>"Who stars in the movie this mural is based of?"}, deleted: false, atype: "activity_code"},
  {activity_id: 97, atype_old: nil, value: {"id"=>"6"}, deleted: false, atype: "beacon"},
  {activity_id: 97, atype_old: nil, value: {"description"=>"Take a selfie with the swan."}, deleted: false, atype: "image"},
  {activity_id: 48, atype_old: nil, value: {"description"=>"Post your wedding story, engagement saga, or simply the most romantic story you have ever heard! "}, deleted: true, atype: "post"},
  {activity_id: 49, atype_old: nil, value: {"description"=>"Pose with a partner on the bridge."}, deleted: false, atype: "image"},
  {activity_id: 76, atype_old: nil, value: {"description"=>"Take a selfie with the rooster."}, deleted: false, atype: "image"},
  {activity_id: 98, atype_old: nil, value: {"id"=>"bull", "description"=>"What animal is depicted on this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 78, atype_old: nil, value: {"description"=>"Take a photo of this mural."}, deleted: false, atype: "image"},
  {activity_id: 74, atype_old: nil, value: {"description"=>"Take a selfie and use the caption \"Ever After.\""}, deleted: false, atype: "image"},
  {activity_id: 61, atype_old: nil, value: {"id"=>"3", "description"=>"How many Yerman monsters are depicted in this mural? "}, deleted: false, atype: "activity_code"},
  {activity_id: 99, atype_old: nil, value: {"id"=>"9"}, deleted: false, atype: "beacon"},
  {activity_id: 110, atype_old: nil, value: {"id"=>"6"}, deleted: true, atype: "beacon"},
  {activity_id: 101, atype_old: nil, value: {"id"=>"5", "description"=>"How many meerkats are depicted in this sculpture?"}, deleted: false, atype: "activity_code"},
  {activity_id: 102, atype_old: nil, value: {"description"=>"Snap a photo of the lightning bolt."}, deleted: false, atype: "image"},
  {activity_id: 100, atype_old: nil, value: {"id"=>"3", "description"=>"How many Yermans are depicted in this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 104, atype_old: nil, value: {"description"=>"Take a silly face selfie with a Morgan Monster."}, deleted: false, atype: "image"},
  {activity_id: 103, atype_old: nil, value: {"id"=>"forever", "description"=>"Fill in the blank: \"Love _______\""}, deleted: false, atype: "activity_code"},
  {activity_id: 105, atype_old: nil, value: {"description"=>"Tell which artist you'd like to see take over the Art Motel next!"}, deleted: false, atype: "post"},
  {activity_id: 106, atype_old: nil, value: {"description"=>"Look into the eye of the Horned Toad and snap a picture."}, deleted: false, atype: "image"},
  {activity_id: 109, atype_old: nil, value: {"id"=>"ever after", "description"=>"What powerful words are depicted in this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 110, atype_old: nil, value: {"description"=>"Strike a pose next to the swan."}, deleted: false, atype: "image"},
  {activity_id: 111, atype_old: nil, value: {"id"=>"100", "description"=>"What is the value of the poker chips depicted in this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 112, atype_old: nil, value: {"description"=>"What do you think of this piece?"}, deleted: false, atype: "post"},
  {activity_id: 114, atype_old: nil, value: {"id"=>"linus", "description"=>"Which Peanuts character is depicted in this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 113, atype_old: nil, value: {"id"=>"taker", "description"=>"Fill in the blank: \"Be a maker! Not a _____!\""}, deleted: false, atype: "activity_code"},
  {activity_id: 100, atype_old: nil, value: {"id"=>"4"}, deleted: false, atype: "beacon"},
  {activity_id: 105, atype_old: nil, value: {"id"=>"5"}, deleted: false, atype: "beacon"},
  {activity_id: 115, atype_old: nil, value: {"id"=>"linus", "description"=>"Which character from Peanuts is depicted in this piece?"}, deleted: false, atype: "activity_code"},
  {activity_id: 116, atype_old: nil, value: {"id"=>"2", "description"=>"How many tanker trucks are used to create this sculpture?"}, deleted: false, atype: "activity_code"},
  {activity_id: 117, atype_old: nil, value: {"id"=>"linus", "description"=>"Which character from Peanuts is depicted in this piece?"}, deleted: false, atype: "activity_code"},
  {activity_id: 118, atype_old: nil, value: {"id"=>"2", "description"=>"How many tanker trucks are used to create this sculpture?"}, deleted: false, atype: "activity_code"},
  {activity_id: 119, atype_old: nil, value: {"id"=>"linus", "description"=>"Which character from Peanuts is depicted in this piece?"}, deleted: false, atype: "activity_code"},
  {activity_id: 120, atype_old: nil, value: {"id"=>"2", "description"=>"How many tanker trucks are used to create this sculpture?"}, deleted: false, atype: "activity_code"},
  {activity_id: 50, atype_old: nil, value: {"id"=>"12"}, deleted: false, atype: "beacon"},
  {activity_id: 48, atype_old: nil, value: {"id"=>"9"}, deleted: false, atype: "beacon"},
  {activity_id: 121, atype_old: nil, value: {"description"=>"What do you think she left him for?"}, deleted: false, atype: "post"},
  {activity_id: 217, atype_old: nil, value: {"id"=>"5"}, deleted: false, atype: "beacon"},
  {activity_id: 217, atype_old: nil, value: {"description"=>"Take a selfie with Ms. N and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 218, atype_old: nil, value: {"id"=>"4"}, deleted: false, atype: "beacon"},
  {activity_id: 218, atype_old: nil, value: {"description"=>"Take a selfie with Mr. A and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 219, atype_old: nil, value: {"id"=>"14"}, deleted: false, atype: "beacon"},
  {activity_id: 219, atype_old: nil, value: {"description"=>"Take a selfie with Ms. S and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 220, atype_old: nil, value: {"id"=>"2"}, deleted: false, atype: "beacon"},
  {activity_id: 221, atype_old: nil, value: {"id"=>"1"}, deleted: false, atype: "beacon"},
  {activity_id: 46, atype_old: nil, value: {"id"=>"8"}, deleted: false, atype: "beacon"},
  {activity_id: 123, atype_old: nil, value: {"description"=>"12"}, deleted: false, atype: "post"},
  {activity_id: 124, atype_old: nil, value: {"description"=>"12"}, deleted: false, atype: "post"},
  {activity_id: 127, atype_old: nil, value: {"description"=>"Take a silly face selfie with a Morgan Monster."}, deleted: false, atype: "image"},
  {activity_id: 126, atype_old: nil, value: {"id"=>"2", "description"=>"How many tanker trucks are used to create this sculpture?"}, deleted: false, atype: "activity_code"},
  {activity_id: 220, atype_old: nil, value: {"description"=>"Take a selfie with Ms. C and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 125, atype_old: nil, value: {"id"=>"3", "description"=>"How many tanker trucks are used to create this sculpture?"}, deleted: false, atype: "activity_code"},
  {activity_id: 128, atype_old: nil, value: {"description"=>"Tell which artist you'd like to see take over the Art Motel next!"}, deleted: false, atype: "post"},
  {activity_id: 129, atype_old: nil, value: {"id"=>"5", "description"=>"How many meerkats are depicted in this sculpture?"}, deleted: false, atype: "activity_code"},
  {activity_id: 126, atype_old: nil, value: {"id"=>"12"}, deleted: true, atype: "beacon"},
  {activity_id: 221, atype_old: nil, value: {"description"=>"Take a selfie with Ms. A and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 222, atype_old: nil, value: {"id"=>"15"}, deleted: false, atype: "beacon"},
  {activity_id: 131, atype_old: nil, value: {"id"=>"forever", "description"=>"Fill in the blank: \"Love _______\""}, deleted: false, atype: "activity_code"},
  {activity_id: 132, atype_old: nil, value: {"id"=>"linus", "description"=>"Which character from Peanuts is depicted in this piece?"}, deleted: false, atype: "activity_code"},
  {activity_id: 130, atype_old: nil, value: {"description"=>"Snap a photo of the lightning bolt."}, deleted: false, atype: "image"},
  {activity_id: 133, atype_old: nil, value: {"id"=>"linus", "description"=>"Which character from Peanuts is depicted in this piece?"}, deleted: false, atype: "activity_code"},
  {activity_id: 134, atype_old: nil, value: {"description"=>"Snap a photo of the lightning bolt."}, deleted: false, atype: "image"},
  {activity_id: 135, atype_old: nil, value: {"id"=>"linus", "description"=>"Which character from Peanuts is depicted in this piece?"}, deleted: false, atype: "activity_code"},
  {activity_id: 136, atype_old: nil, value: {"description"=>"Snap a photo of the lightning bolt."}, deleted: false, atype: "image"},
  {activity_id: 137, atype_old: nil, value: {"id"=>"100", "description"=>"What is the value of the poker chips depicted in this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 139, atype_old: nil, value: {"description"=>"Look into the eye of the Horned Toad and snap a picture."}, deleted: false, atype: "image"},
  {activity_id: 140, atype_old: nil, value: {"description"=>"What do you think of this piece?"}, deleted: false, atype: "post"},
  {activity_id: 141, atype_old: nil, value: {"id"=>"ever after", "description"=>"What powerful words are depicted in this mural?"}, deleted: false, atype: "activity_code"},
  {activity_id: 142, atype_old: nil, value: {"id"=>"taker", "description"=>"Fill in the blank: \"Be a maker! Not a _____!\""}, deleted: false, atype: "activity_code"},
  {activity_id: 143, atype_old: nil, value: {"description"=>"Strike a pose next to the swan."}, deleted: false, atype: "image"},
  {activity_id: 125, atype_old: nil, value: {"id"=>"4"}, deleted: true, atype: "beacon"},
  {activity_id: 128, atype_old: nil, value: {"id"=>"5"}, deleted: true, atype: "beacon"},
  {activity_id: 143, atype_old: nil, value: {"id"=>"6"}, deleted: true, atype: "beacon"},
  {activity_id: 147, atype_old: nil, value: {"description"=>"12"}, deleted: false, atype: "post"},
  {activity_id: 148, atype_old: nil, value: {"description"=>"12"}, deleted: false, atype: "post"},
  {activity_id: 144, atype_old: nil, value: {"description"=>"Take a photo of the sustenance you speak of!"}, deleted: false, atype: "image"},
  {activity_id: 145, atype_old: nil, value: {"id"=>"13"}, deleted: false, atype: "beacon"},
  {activity_id: 150, atype_old: nil, value: {"id"=>"1988", "description"=>"Enter the four-digit year as the code."}, deleted: false, atype: "activity_code"},
  {activity_id: 151, atype_old: nil, value: {"id"=>"8", "description"=>"Even if you don't have the straw-chugging in you, you can still complete this task by entering the number on Rex's jersey."}, deleted: false, atype: "activity_code"},
  {activity_id: 152, atype_old: nil, value: {"id"=>"1902", "description"=>"Enter the code/answer in the form of the four-digit year."}, deleted: false, atype: "activity_code"},
  {activity_id: 153, atype_old: nil, value: {"description"=>"Do you have a unique Margarita recipe? Post it!"}, deleted: false, atype: "post"},
  {activity_id: 154, atype_old: nil, value: {"description"=>"Record a little snippet of the train wreck that is your fellow-fan remix."}, deleted: false, atype: "audio"},
  {activity_id: 155, atype_old: nil, value: {"id"=>"13"}, deleted: false, atype: "beacon"},
  {activity_id: 156, atype_old: nil, value: {"description"=>"Take a photo, selfie, or abstract photo of your team's merch. Take the challenge to the next level and see if you can find someone in uniform!"}, deleted: false, atype: "image"},
  {activity_id: 222, atype_old: nil, value: {"description"=>"Take a selfie with Mr. R and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 223, atype_old: nil, value: {"id"=>"16"}, deleted: false, atype: "beacon"},
  {activity_id: 223, atype_old: nil, value: {"description"=>"Tell everyone how much fun you had and don't forget to share for your chance to win!"}, deleted: false, atype: "post"},
  {activity_id: 225, atype_old: nil, value: {"id"=>"5"}, deleted: false, atype: "beacon"},
  {activity_id: 225, atype_old: nil, value: {"description"=>"Take a selfie with Ms. N and post it to your feed."}, deleted: false, atype: "image"},
  {activity_id: 226, atype_old: nil, value: {"id"=>"4"}, deleted: false, atype: "beacon"},
  {activity_id: 227, atype_old: nil, value: {"id"=>"14"}, deleted: false, atype: "beacon"},
  {activity_id: 226, atype_old: nil, value: {"description"=>"Take a selfie with Mr. A and post it to your feed."}, deleted: false, atype: "image"},
  {activity_id: 227, atype_old: nil, value: {"description"=>"Take a selfie with Ms. S and post it to your feed."}, deleted: false, atype: "image"},
  {activity_id: 228, atype_old: nil, value: {"id"=>"2"}, deleted: false, atype: "beacon"},
  {activity_id: 228, atype_old: nil, value: {"description"=>"Take a selfie with Ms. C and post it to your feed."}, deleted: false, atype: "image"},
  {activity_id: 229, atype_old: nil, value: {"id"=>"1"}, deleted: false, atype: "beacon"},
  {activity_id: 229, atype_old: nil, value: {"description"=>"Take a selfie with Ms. A and post it to your feed."}, deleted: false, atype: "image"},
  {activity_id: 230, atype_old: nil, value: {"id"=>"15"}, deleted: false, atype: "beacon"},
  {activity_id: 230, atype_old: nil, value: {"description"=>"Take a selfie with Mr. Rand post it to your feed."}, deleted: false, atype: "image"},
  {activity_id: 231, atype_old: nil, value: {"id"=>"16"}, deleted: false, atype: "beacon"},
  {activity_id: 231, atype_old: nil, value: {"description"=>"Tell us how much fun you had! Don't forget to share for your chance to win!"}, deleted: false, atype: "post"},
  {activity_id: 232, atype_old: nil, value: {"id"=>"16"}, deleted: false, atype: "beacon"},
  {activity_id: 233, atype_old: nil, value: {"description"=>"Post a selfie showing your excitement!"}, deleted: false, atype: "image"},
  {activity_id: 234, atype_old: nil, value: {"id"=>"5"}, deleted: false, atype: "beacon"},
  {activity_id: 234, atype_old: nil, value: {"description"=>"Take a selfie with Ms. N and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 235, atype_old: nil, value: {"id"=>"4"}, deleted: false, atype: "beacon"},
  {activity_id: 236, atype_old: nil, value: {"id"=>"14"}, deleted: false, atype: "beacon"},
  {activity_id: 236, atype_old: nil, value: {"description"=>"Take a selfie with Ms. S and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 237, atype_old: nil, value: {"id"=>"2"}, deleted: false, atype: "beacon"},
  {activity_id: 235, atype_old: nil, value: {"description"=>"Take a selfie with Mr. A and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 237, atype_old: nil, value: {"description"=>"Take a selfie with Ms. C and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 238, atype_old: nil, value: {"description"=>"Take a selfie with Ms. A and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 239, atype_old: nil, value: {"description"=>"Take a selfie with Mr. R and post it to the feed."}, deleted: false, atype: "image"},
  {activity_id: 240, atype_old: nil, value: {"description"=>"Let us know how much you enjoyed your quest! Don't forget to share to be entered to win the amazing prizes!"}, deleted: false, atype: "post"},
  {activity_id: 240, atype_old: nil, value: {"id"=>"17"}, deleted: false, atype: "beacon"},
  {activity_id: 238, atype_old: nil, value: {"id"=>"connect", "description"=>"undefined"}, deleted: false, atype: "activity_code"},
  {activity_id: 239, atype_old: nil, value: {"id"=>"nascar", "description"=>"undefined"}, deleted: false, atype: "activity_code"},
  {activity_id: 144, atype_old: nil, value: {"description"=>"Tell future patrons what your favorite item on Twin Peaks' menu is, and WHY! Give a recommendation for someone who has never eaten here before. Is this your first time? Share your experience!"}, deleted: false, atype: "post"}
])
