ActionType.create!(name: "Complete Quest", internal_name: "complete_quest")
ActionType.create!(name: "Complete Profile", internal_name: "complete_profile")
ActionType.create!(name: "Share Post To Person",  internal_name: "share_post_person")
ActionType.create!(name: "Share Post", internal_name: "share_post")
ActionType.create!(name: "Chat 10 Minute Dailys", internal_name: "chat_10_daily", seconds_lag: 86400)
ActionType.create!(name: "Chat 30 Minutes Daily", internal_name: "chat_30_daily", seconds_lag: 86400)
ActionType.create!(name: "Chat 60 Minutes Daily", internal_name: "chat_60_daily", seconds_lag: 86400)
ActionType.create!(name: "Invite Person", internal_name: "invite_person")
ActionType.create!(name: "Open App Daily", internal_name: "open_app_daily", seconds_lag: 86400)
ActionType.create!(name: "Follow Person", internal_name: "follow_person")
ActionType.create!(name: "React to Post", internal_name: "react_post")
