PostCommentReport.create!([
  {post_comment_id: 1471, person_id: 53, reason: nil, status: "comment_hidden"},
  {post_comment_id: 1489, person_id: 53, reason: nil, status: "comment_hidden"},
  {post_comment_id: 1485, person_id: 53, reason: nil, status: "comment_hidden"},
  {post_comment_id: 1486, person_id: 53, reason: nil, status: "comment_hidden"},
  {post_comment_id: 1487, person_id: 53, reason: nil, status: "comment_hidden"},
  {post_comment_id: 1488, person_id: 53, reason: nil, status: "comment_hidden"},
  {post_comment_id: 1492, person_id: 53, reason: nil, status: "comment_hidden"},
  {post_comment_id: 1491, person_id: 53, reason: nil, status: "comment_hidden"},
  {post_comment_id: 1490, person_id: 53, reason: nil, status: "comment_hidden"},
  {post_comment_id: 1552, person_id: 36, reason: "spam", status: "comment_hidden"},
  {post_comment_id: 1551, person_id: 36, reason: "spam", status: "comment_hidden"},
  {post_comment_id: 1553, person_id: 36, reason: "spam", status: "no_action_needed"},
  {post_comment_id: 1540, person_id: 4641, reason: "spam", status: "no_action_needed"},
  {post_comment_id: 1538, person_id: 4641, reason: "spam", status: "comment_hidden"},
  {post_comment_id: 1528, person_id: 4641, reason: "spam", status: "comment_hidden"},
  {post_comment_id: 2639, person_id: 6285, reason: "how ya doin?)", status: "no_action_needed"},
  {post_comment_id: 4294, person_id: 2501, reason: "yeees😊", status: "no_action_needed"},
  {post_comment_id: 4676, person_id: 8197, reason: "spam", status: "comment_hidden"},
  {post_comment_id: 4676, person_id: 8259, reason: nil, status: "comment_hidden"},
  {post_comment_id: 4824, person_id: 8096, reason: "😘❤️ Roumanie 🇷🇴", status: "no_action_needed"},
  {post_comment_id: 6463, person_id: 3623, reason: "right", status: "no_action_needed"},
  {post_comment_id: 6768, person_id: 3623, reason: "good", status: "no_action_needed"},
  {post_comment_id: 6802, person_id: 3623, reason: "good friends", status: "comment_hidden"},
  {post_comment_id: 6806, person_id: 3623, reason: "hello friends", status: "no_action_needed"},
  {post_comment_id: 7466, person_id: 11367, reason: "facks", status: "no_action_needed"},
  {post_comment_id: 7505, person_id: 11069, reason: "it's something ugly", status: "comment_hidden"},
  {post_comment_id: 7639, person_id: 10589, reason: nil, status: "no_action_needed"},
  {post_comment_id: 7684, person_id: 12276, reason: "continut neeadecvat", status: "comment_hidden"},
  {post_comment_id: 10265, person_id: 17397, reason: "hensnshahsbs", status: "comment_hidden"},
  {post_comment_id: 10599, person_id: 21060, reason: "instigă la ură", status: "comment_hidden"}
])
