PostReport.create!([
  {post_id: 23, person_id: 32, reason: "cuz", status: "post_hidden"},
  {post_id: 53, person_id: 12, reason: "test", status: "pending"},
  {post_id: 53, person_id: 12, reason: "test", status: "pending"},
  {post_id: 233, person_id: 93, reason: "jaghsjen", status: "post_hidden"},
  {post_id: 233, person_id: 93, reason: "gdjdhdh", status: "post_hidden"},
  {post_id: 184, person_id: 93, reason: "too cutesy!", status: "post_hidden"},
  {post_id: 222, person_id: 93, reason: "too funny", status: "post_hidden"},
  {post_id: 232, person_id: 93, reason: "", status: "post_hidden"},
  {post_id: 232, person_id: 93, reason: "cos", status: "post_hidden"},
  {post_id: 232, person_id: 93, reason: "becos ", status: "post_hidden"},
  {post_id: 233, person_id: 93, reason: "", status: "post_hidden"},
  {post_id: 54, person_id: 3, reason: "Too awesome", status: "pending"},
  {post_id: 54, person_id: 3, reason: "too awesome", status: "pending"},
  {post_id: 869, person_id: 415, reason: "and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker1234567810", status: "post_hidden"},
  {post_id: 869, person_id: 415, reason: "and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker1234567891", status: "no_action_needed"},
  {post_id: 846, person_id: 386, reason: "test report post", status: "no_action_needed"},
  {post_id: 1061, person_id: 439, reason: "", status: "post_hidden"},
  {post_id: 1164, person_id: 287, reason: "blank", status: "post_hidden"},
  {post_id: 1854, person_id: 2777, reason: nil, status: "no_action_needed"},
  {post_id: 2078, person_id: 3418, reason: nil, status: "post_hidden"},
  {post_id: 699, person_id: 2746, reason: "T", status: "no_action_needed"},
  {post_id: 2591, person_id: 4344, reason: nil, status: "post_hidden"},
  {post_id: 2792, person_id: 2501, reason: "#inna #nohelp", status: "no_action_needed"},
  {post_id: 2362, person_id: 4647, reason: "💜💜💜💜", status: "no_action_needed"},
  {post_id: 3534, person_id: 3201, reason: "its very offensive and its sexual and nudity", status: "post_hidden"},
  {post_id: 3532, person_id: 3201, reason: "its offensive and contains nudity", status: "post_hidden"},
  {post_id: 3531, person_id: 3201, reason: "its offensive and containe nudity", status: "post_hidden"},
  {post_id: 3542, person_id: 3201, reason: "nudity", status: "post_hidden"},
  {post_id: 3541, person_id: 3201, reason: "nudity", status: "post_hidden"},
  {post_id: 3540, person_id: 3201, reason: "nudity", status: "post_hidden"},
  {post_id: 3531, person_id: 2768, reason: "fake insults innapropriate contents", status: "post_hidden"},
  {post_id: 3534, person_id: 2768, reason: "porno, highly innapropriate,", status: "post_hidden"},
  {post_id: 3531, person_id: 2768, reason: "fake and insult", status: "post_hidden"},
  {post_id: 3537, person_id: 2768, reason: "please ban this person", status: "post_hidden"},
  {post_id: 3517, person_id: 704, reason: "I report it so Inna knows it has been posted here. If she is okay with it, you don't have to remove it. Thanks!", status: "post_hidden"},
  {post_id: 3700, person_id: 4636, reason: "spam", status: "no_action_needed"},
  {post_id: 3697, person_id: 4636, reason: "spam", status: "no_action_needed"},
  {post_id: 3682, person_id: 557, reason: "Why a computer keypad?", status: "post_hidden"},
  {post_id: 3660, person_id: 6075, reason: "Spam", status: "no_action_needed"},
  {post_id: 3959, person_id: 4641, reason: "spam and cropped", status: "no_action_needed"},
  {post_id: 3588, person_id: 386, reason: nil, status: "post_hidden"},
  {post_id: 1241, person_id: 417, reason: nil, status: "post_hidden"},
  {post_id: 1322, person_id: 417, reason: nil, status: "post_hidden"},
  {post_id: 1065, person_id: 417, reason: nil, status: "post_hidden"},
  {post_id: 4098, person_id: 4641, reason: "test", status: "no_action_needed"},
  {post_id: 3675, person_id: 4636, reason: "ultra spam hidden adds links malicious", status: "post_hidden"},
  {post_id: 4659, person_id: 4641, reason: "irelevant", status: "post_hidden"},
  {post_id: 4660, person_id: 4641, reason: "irrelevant", status: "post_hidden"},
  {post_id: 4983, person_id: 4641, reason: "no politics", status: "post_hidden"},
  {post_id: 4967, person_id: 4641, reason: "no politics", status: "post_hidden"},
  {post_id: 6131, person_id: 8051, reason: nil, status: "no_action_needed"},
  {post_id: 6353, person_id: 381, reason: nil, status: "post_hidden"},
  {post_id: 6359, person_id: 381, reason: nil, status: "post_hidden"},
  {post_id: 7469, person_id: 2460, reason: "10 kasım is not bayram. Ataturk's death day.", status: "post_hidden"},
  {post_id: 7513, person_id: 8925, reason: nil, status: "no_action_needed"},
  {post_id: 7513, person_id: 8925, reason: nil, status: "no_action_needed"},
  {post_id: 7671, person_id: 4641, reason: "spam", status: "post_hidden"},
  {post_id: 2342, person_id: 9187, reason: nil, status: "no_action_needed"},
  {post_id: 1764, person_id: 9187, reason: "you ar my hort!!!", status: "no_action_needed"},
  {post_id: 8310, person_id: 333, reason: nil, status: "post_hidden"},
  {post_id: 8404, person_id: 4641, reason: "spam", status: "post_hidden"},
  {post_id: 8406, person_id: 4641, reason: "spam", status: "post_hidden"},
  {post_id: 8405, person_id: 4641, reason: "spam", status: "post_hidden"},
  {post_id: 8402, person_id: 4641, reason: nil, status: "post_hidden"},
  {post_id: 8411, person_id: 4641, reason: nil, status: "post_hidden"},
  {post_id: 8412, person_id: 4641, reason: nil, status: "post_hidden"},
  {post_id: 8825, person_id: 9641, reason: "It's very beautiful", status: "no_action_needed"},
  {post_id: 8969, person_id: 333, reason: nil, status: "post_hidden"},
  {post_id: 9013, person_id: 6487, reason: "no nice crisu3", status: "no_action_needed"},
  {post_id: 11814, person_id: 15306, reason: "Mi a furat poza", status: "post_hidden"},
  {post_id: 11840, person_id: 16424, reason: "prost", status: "post_hidden"},
  {post_id: 12107, person_id: 18509, reason: nil, status: "post_hidden"},
  {post_id: 12149, person_id: 16363, reason: nil, status: "no_action_needed"},
  {post_id: 12090, person_id: 18509, reason: "persoana e foarte proastă", status: "no_action_needed"},
  {post_id: 12262, person_id: 18509, reason: nil, status: "no_action_needed"},
  {post_id: 11791, person_id: 20732, reason: nil, status: "no_action_needed"},
  {post_id: 12938, person_id: 20942, reason: "imi place", status: "no_action_needed"},
  {post_id: 13335, person_id: 10562, reason: "este neadegvat", status: "no_action_needed"},
  {post_id: 8900, person_id: 321, reason: nil, status: "post_hidden"},
  {post_id: 14446, person_id: 20166, reason: "Este o poza cu Diana C si aplicația este a Irinei Deaconescu 😡", status: "post_hidden"},
  {post_id: 14446, person_id: 20166, reason: "Ștergeți pozaaaaaa", status: "post_hidden"},
  {post_id: 13727, person_id: 22859, reason: "looks too cold", status: "post_hidden"},
  {post_id: 14932, person_id: 23337, reason: nil, status: "no_action_needed"},
  {post_id: 14922, person_id: 11893, reason: nil, status: "post_hidden"},
  {post_id: 12028, person_id: 22939, reason: nil, status: "no_action_needed"}
])
