Product.create!([
  {name: "Admin", internal_name: "admin", enabled: true, can_have_supers: true, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "Smiley", internal_name: "smiley", enabled: true, can_have_supers: false, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "Adara", internal_name: "adara", enabled: true, can_have_supers: false, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "NBC", internal_name: "nbc", enabled: true, can_have_supers: false, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "INNA", internal_name: "inna", enabled: true, can_have_supers: false, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "Starmaker", internal_name: "starmaker", enabled: true, can_have_supers: true, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "FanLink", internal_name: "fanlink_internal_testing", enabled: true, can_have_supers: false, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "Bubba", internal_name: "bubba", enabled: true, can_have_supers: true, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "LV Connect", internal_name: "lvconnect", enabled: true, can_have_supers: false, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "Orlando Connect", internal_name: "orlandoconnect", enabled: true, can_have_supers: false, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "Bucharest Connect", internal_name: "bucharestconnect", enabled: true, can_have_supers: false, age_requirement: 0, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "Irinassw Fan App", internal_name: "irinassw", enabled: true, can_have_supers: false, age_requirement: 18, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "Nashville Connect", internal_name: "nashvilleconnect", enabled: true, can_have_supers: false, age_requirement: 21, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0},
  {name: "420Friendly", internal_name: "cannapp", enabled: true, can_have_supers: false, age_requirement: 21, logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, color_primary: "4B73D7", color_primary_text: "FFFFFF", color_secondary: "CDE5FF", color_secondary_text: "000000", color_tertiary: "FFFFFF", color_tertiary_text: "000000", color_accent: "FFF537", color_accent_text: "FFF537", color_title_text: "FFF537", color_accessory: "000000", navigation_bar_style: 1, status_bar_style: 1, toolbar_style: 1, features: 0}
])
