inherit_gem:
  rubocop-rails:
    - config/rails.yml


AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

