image: ruby:2.5.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - gem install --install-dir ./vendor/bundler bundler -bindir ./vendor/bundler/bin/
          - ./vendor/bundler/bin/bundle install --path vendor/bundle
          - ./vendor/bundler/bin/bundle exec rake db:setup
          - ./vendor/bundler/bin/bundle exec rake db:test:prepare
          - ./vendor/bundler/bin/bundle exec rspec .
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: fanlink_test
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user_password
  caches:
    bundler: vendor/bundle
