image: ruby:2.5.1

pipelines:
  default:
    - step:
        caches:
          - bundler
        script: # Modify the commands below to build your repository.
          - gem install bundler -v '2.0.1'
          - bundle install --path vendor/bundle
          - RAILS_ENV=test bundle exec rake db:reset
          - RAILS_ENV=test bundle exec rake db:setup
          - RAILS_ENV=test bundle exec rake db:test:prepare
          - RAILS_ENV=test bundle exec rspec spec --exclude-pattern "spec/requests/**/*_spec.rb"
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: fanlink_test
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user_password

  caches:
    bundler: vendor/bundle
