image: ruby:2.5.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - export FANLINK_PG_USER=test_user
          - export FANLINK_PG_PASSWORD=test_user_password
          - export FANLINK_PG_HOST=localhost
          - bundle install
          - bundle exec rake db:setup
          - bundle exec rake db:test:prepare
          - bundle exec rspec .
        services:
          - postgres
 
definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: fanlink_test
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user_password
  caches:
    bundler: vendor/bundle
