image: ruby:2.5.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - gem install bundler
          - bundle install
          - RAILS_ENV=test bundle exec rake db:reset
          - RAILS_ENV=test bundle exec rake db:setup
          - RAILS_ENV=test bundle exec rake db:test:prepare
          - RAILS_ENV=test bundle exec rspec . 
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: fanlink_test
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user_password
