Certcourse.create( id: 16, long_name: "Test no pages 8", short_name: "Test no pages 8", description: "Test no pages 8", color_hex: "#000000", status: "entry", duration: 5568798, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Mon, 11 Mar 2019 18:34:20 UTC +00:00"), updated_at: DateTime.parse("Mon, 11 Mar 2019 18:34:20 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 17, long_name: "Test no pages 9", short_name: "Test no pages 9", description: "Test no pages 9", color_hex: "#000000", status: "live", duration: 100000, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Mon, 11 Mar 2019 18:34:41 UTC +00:00"), updated_at: DateTime.parse("Mon, 11 Mar 2019 18:34:41 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 18, long_name: "Test no pages 10", short_name: "Test no pages 10", description: "Test no pages 10", color_hex: "#000000", status: "live", duration: 5545877, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Tue, 12 Mar 2019 14:33:18 UTC +00:00"), updated_at: DateTime.parse("Tue, 12 Mar 2019 14:34:15 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 1, long_name: "Course number 1", short_name: "Crs 1", description: "First course ever", color_hex: "#000000", status: "live", duration: 10000, is_completed: true, copyright_text: "do not copy this", created_at: DateTime.parse("Thu, 21 Feb 2019 15:17:11 UTC +00:00"), updated_at: DateTime.parse("Thu, 21 Feb 2019 15:17:11 UTC +00:00"), product_id: 14, certcourse_pages_count: 7) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 2, long_name: "Course number 2", short_name: "Crs 2", description: "Second course ever", color_hex: "#FF0000", status: "live", duration: 10000, is_completed: true, copyright_text: "do not copy this", created_at: DateTime.parse("Thu, 21 Feb 2019 15:17:29 UTC +00:00"), updated_at: DateTime.parse("Wed, 27 Feb 2019 13:33:06 UTC +00:00"), product_id: 14, certcourse_pages_count: 0) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 3, long_name: "Free Course no.1", short_name: "free1", description: "free course 1", color_hex: "#0000FF", status: "entry", duration: 10000, is_completed: false, copyright_text: "blabla", created_at: DateTime.parse("Fri, 22 Feb 2019 11:27:53 UTC +00:00"), updated_at: DateTime.parse("Wed, 27 Feb 2019 13:33:19 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 4, long_name: "Free Course no.2", short_name: "free2", description: "free course 2", color_hex: "#000000", status: "entry", duration: 10000, is_completed: false, copyright_text: "blablablablalba", created_at: DateTime.parse("Fri, 22 Feb 2019 11:28:15 UTC +00:00"), updated_at: DateTime.parse("Fri, 22 Feb 2019 11:28:15 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 5, long_name: "Nevada Dispensary Basics", short_name: "Needy Bee", description: "Your first step towards cannabis enlightment", color_hex: "#000000", status: "live", duration: 3600, is_completed: false, copyright_text:       "You shall not copy this course, or the cannabis warlord will find you", created_at: DateTime.parse("Thu, 07 Mar 2019 17:37:14 UTC +00:00"), updated_at: DateTime.parse("Fri, 08 Mar 2019 07:37:18 UTC +00:00"), product_id: 14, certcourse_pages_count: 39) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 6, long_name: "Nevada Dispensary Basics Mix", short_name: "Needy Bee Mix", description: "Your first step towards cannabis enlightment", color_hex: "#000000", status: "entry", duration: 3600, is_completed: false, copyright_text:       "You shall not copy this course, or the cannabis warlord will find you", created_at: DateTime.parse("Fri, 08 Mar 2019 15:07:54 UTC +00:00"), updated_at: DateTime.parse("Sun, 10 Mar 2019 14:16:44 UTC +00:00"), product_id: 14, certcourse_pages_count: 39 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 7, long_name: "Nevada Dispensary Basics FREE", short_name: "Needy Bee FREE", description: "Your first step towards cannabis enlightment", color_hex: "#000000", status: "live", duration: 3600, is_completed: false, copyright_text:       "You shall not copy this course, or the cannabis warlord will find you", created_at: DateTime.parse("Fri, 08 Mar 2019 17:21:43 UTC +00:00"), updated_at: DateTime.parse("Sun, 10 Mar 2019 14:16:59 UTC +00:00"), product_id: 14, certcourse_pages_count: 39 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 8, long_name: "Certcourse business test", short_name: "cert bus test", description: "Testing the creation of a certificate", color_hex: "#000000", status: "live", duration: 100, is_completed: false, copyright_text: "do not copy", created_at: DateTime.parse("Mon, 11 Mar 2019 13:46:28 UTC +00:00"), updated_at: DateTime.parse("Mon, 11 Mar 2019 14:25:01 UTC +00:00"), product_id: 14, certcourse_pages_count: 3 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 9, long_name: "Test no pages 1", short_name: "Test no pages 1", description: "There are no pages in this course", color_hex: "#000000", status: "live", duration: 0, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Mon, 11 Mar 2019 18:00:14 UTC +00:00"), updated_at: DateTime.parse("Mon, 11 Mar 2019 18:00:14 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 10, long_name: "Test no pages 2", short_name: "Test no pages 2", description: "Test no pages 2", color_hex: "#000000", status: "live", duration: 1000, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Mon, 11 Mar 2019 18:00:43 UTC +00:00"), updated_at: DateTime.parse("Mon, 11 Mar 2019 18:00:43 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 11, long_name: "Test no pages 3", short_name: "Test no pages 3", description: "Test no pages 3", color_hex: "#000000", status: "live", duration: 0, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Mon, 11 Mar 2019 18:00:59 UTC +00:00"), updated_at: DateTime.parse("Mon, 11 Mar 2019 18:00:59 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 12, long_name: "Test no pages 4", short_name: "Test no pages 4", description: "Test no pages 4", color_hex: "#000000", status: "live", duration: 5888777, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Mon, 11 Mar 2019 18:01:28 UTC +00:00"), updated_at: DateTime.parse("Mon, 11 Mar 2019 18:01:28 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 13, long_name: "Test no pages 5", short_name: "Test no pages 5", description: "Test no pages 5", color_hex: "#000000", status: "live", duration: 68978, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Mon, 11 Mar 2019 18:01:48 UTC +00:00"), updated_at: DateTime.parse("Mon, 11 Mar 2019 18:01:48 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 14, long_name: "Test no pages 6", short_name: "Test no pages 6", description: "Test no pages 6", color_hex: "#000000", status: "live", duration: 0, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Mon, 11 Mar 2019 18:33:43 UTC +00:00"), updated_at: DateTime.parse("Mon, 11 Mar 2019 18:33:43 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 15, long_name: "Test no pages 7", short_name: "Test no pages 7", description: "Test no pages 7", color_hex: "#000000", status: "live", duration: 0, is_completed: false, copyright_text: "texgt", created_at: DateTime.parse("Mon, 11 Mar 2019 18:33:59 UTC +00:00"), updated_at: DateTime.parse("Mon, 11 Mar 2019 18:33:59 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 19, long_name: "Test no pages 11", short_name: "Test no pages 11", description: "Test no pages 11", color_hex: "#FF6347", status: "live", duration: 0, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Tue, 12 Mar 2019 14:34:04 UTC +00:00"), updated_at: DateTime.parse("Tue, 12 Mar 2019 14:34:04 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 21, long_name: "App 2 Test page 3", short_name: "App 2 test", description: "Couse test on app 2", color_hex: "#000000", status: "live", duration: 1000, is_completed: false, copyright_text: "text", created_at: DateTime.parse("Thu, 14 Mar 2019 13:01:45 UTC +00:00"), updated_at: DateTime.parse("Thu, 14 Mar 2019 13:01:45 UTC +00:00"), product_id: 15, certcourse_pages_count: 3 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 22, long_name: "Test 2nd Caned", short_name: "2nd course on Caned", description: "This is the second one on Cannabis Ed", color_hex: "#b83939", status: "live", duration: 360, is_completed: false, copyright_text: "textinho", created_at: DateTime.parse("Thu, 14 Mar 2019 13:33:03 UTC +00:00"), updated_at: DateTime.parse("Thu, 14 Mar 2019 13:33:03 UTC +00:00"), product_id: 14, certcourse_pages_count: 5 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 55, long_name: "test 3", short_name: "test 3", description: "test 3", color_hex: "#000000", status: "live", duration: 10000, is_completed: false, copyright_text: "1111", created_at: DateTime.parse("Sat, 16 Mar 2019 02:38:07 UTC +00:00"), updated_at: DateTime.parse("Sat, 16 Mar 2019 02:38:07 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 56, long_name: "bus test certcourse", short_name: "bus test 5", description: "description", color_hex: "#000000", status: "live", duration: 3600, is_completed: false, copyright_text: "test QA", created_at: DateTime.parse("Tue, 19 Mar 2019 14:21:16 UTC +00:00"), updated_at: DateTime.parse("Tue, 19 Mar 2019 14:21:16 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 57, long_name: "testUL", short_name: "test", description: "test", color_hex: "#000000", status: "entry", duration: 0, is_completed: false, copyright_text: "ba", created_at: DateTime.parse("Tue, 19 Mar 2019 15:38:58 UTC +00:00"), updated_at: DateTime.parse("Tue, 19 Mar 2019 15:38:58 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 58, long_name: "Bust test for QA 1 - Marius", short_name: "QA test 1", description: "Bust test for QA made by Marius", color_hex: "#000000", status: "entry", duration: 3600, is_completed: false, copyright_text: "QA test", created_at: DateTime.parse("Tue, 19 Mar 2019 15:43:12 UTC +00:00"), updated_at: DateTime.parse("Tue, 19 Mar 2019 15:43:12 UTC +00:00"), product_id: 14, certcourse_pages_count: 0 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 60, long_name: "Marian's First Certificate", short_name: "MFC", description: "Marian's First Certificate", color_hex: "#000000", status: "live", duration: 20, is_completed: false, copyright_text: "Do not touch", created_at: DateTime.parse("Tue, 19 Mar 2019 16:20:02 UTC +00:00"), updated_at: DateTime.parse("Tue, 19 Mar 2019 16:36:05 UTC +00:00"), product_id: 14, certcourse_pages_count: 11 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 20, long_name: "I am long name", short_name: "name", description: "This is the course of how to do nothing.", color_hex: "#000000", status: "live", duration: 567, is_completed: true, copyright_text: "(c) can-ed 2019", created_at: DateTime.parse("Wed, 13 Mar 2019 20:37:13 UTC +00:00"), updated_at: DateTime.parse("Wed, 13 Mar 2019 20:37:13 UTC +00:00"), product_id: 14, certcourse_pages_count: 2 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 59, long_name: "Cip's how to use a camera", short_name: "Cip's how to camera", description: "this is the place to teach you camera operation stuff", color_hex: "#000000", status: "live", duration: 10, is_completed: false, copyright_text: "cip will haunt you if you copy this ", created_at: DateTime.parse("Tue, 19 Mar 2019 15:52:23 UTC +00:00"), updated_at: DateTime.parse("Tue, 19 Mar 2019 16:11:12 UTC +00:00"), product_id: 14, certcourse_pages_count: 4 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 67, long_name: "Cip's Video quiz image Course", short_name: "Cip's Vid quiz img", description: "A simple course with 3 pages and a quiz at the middle", color_hex: "#01b9ff", status: "live", duration: 86400, is_completed: false, copyright_text: "Dobbie is watching you", created_at: DateTime.parse("Wed, 03 Apr 2019 12:45:53 UTC +00:00"), updated_at: DateTime.parse("Wed, 03 Apr 2019 13:01:32 UTC +00:00"), product_id: 14, certcourse_pages_count: 3) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 64, long_name: "Milk from Butter to cheese ", short_name: "Milk 1on1", description: "how to milk ", color_hex: "#ea0e71", status: "live", duration: 100, is_completed: false, copyright_text: "cc milk cc 2019", created_at: DateTime.parse("Wed, 20 Mar 2019 07:52:56 UTC +00:00"), updated_at: DateTime.parse("Wed, 20 Mar 2019 08:58:24 UTC +00:00"), product_id: 14, certcourse_pages_count: 4 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 62, long_name: "Cip's Essential SkillZ Tree share unicorn airplanes", short_name: "Cip's Esse Skillz", description:       "This course will teach you about exactly what you tought it will teach you about", color_hex: "#000000", status: "live", duration: 8600, is_completed: false, copyright_text:       "Cip says - > Please Copy I dare you I double dare you because if i do not dare you then noone else will and that would most likely be sad panda bro you know what i am saying. If you do please copy you bad evul man or woman you", created_at: DateTime.parse("Tue, 19 Mar 2019 18:36:33 UTC +00:00"), updated_at: DateTime.parse("Tue, 19 Mar 2019 19:18:59 UTC +00:00"), product_id: 14, certcourse_pages_count: 17) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 72, long_name: "Cip's quiz wrongs answer page is null", short_name: "Cip's wrong aswer is null", description: "The quiz in this course has the wrong answer page as null", color_hex: "#000000", status: "live", duration: 10, is_completed: false, copyright_text: "Spider pig, spider pig, does whatever a spider pig does", created_at: DateTime.parse("Wed, 17 Apr 2019 13:46:19 UTC +00:00"), updated_at: DateTime.parse("Wed, 17 Apr 2019 13:50:54 UTC +00:00"), product_id: 14, certcourse_pages_count: 2 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 61, long_name: "Cip's how to focus the camera", short_name: "Cips focus tutorial", description: "This course has nothing to do with the title, just sayin", color_hex: "#000000", status: "live", duration: 86000, is_completed: false, copyright_text: "cip says do not copy", created_at: DateTime.parse("Tue, 19 Mar 2019 16:41:22 UTC +00:00"), updated_at: DateTime.parse("Tue, 19 Mar 2019 16:54:12 UTC +00:00"), product_id: 14, certcourse_pages_count: 14 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 74, long_name: "Cips quiz with wrongid answer on an optional quiz", short_name: "Cips wrong id answer on optional quiz", description:       "This course has an optional quiz with a wrong answer page set up to test progression ", color_hex: "#000000", status: "live", duration: 1, is_completed: false, copyright_text: "copycopcycopy cats", created_at: DateTime.parse("Fri, 19 Apr 2019 12:58:47 UTC +00:00"), updated_at: DateTime.parse("Fri, 19 Apr 2019 13:15:11 UTC +00:00"), product_id: 14, certcourse_pages_count: 13 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 73, long_name: "blablaaa cip blaa blaa", short_name: "cip bla", description: "bla bla bla", color_hex: "#000000", status: "entry", duration: 0, is_completed: false, copyright_text: "txt", created_at: DateTime.parse("Thu, 18 Apr 2019 14:58:27 UTC +00:00"), updated_at: DateTime.parse("Thu, 18 Apr 2019 14:58:27 UTC +00:00"), product_id: 14, certcourse_pages_count: 2 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 68, long_name: "Cip's optional quiz with wrong answer page", short_name: "Cip's opt quiz with wrong answe", description:       "The quiz in this course has an optional quiz with wrong answer page", color_hex: "#000000", status: "live", duration: 0, is_completed: false, copyright_text:       "The quiz in this course has the answer page id in another quiz", created_at: DateTime.parse("Thu, 04 Apr 2019 14:43:43 UTC +00:00"), updated_at: DateTime.parse("Thu, 18 Apr 2019 19:52:32 UTC +00:00"), product_id: 14, certcourse_pages_count: 2 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 63, long_name: "Onions setp by step", short_name: "onions", description: "you can learn how to grow one onion", color_hex: "#00cbff", status: "live", duration: 160, is_completed: false, copyright_text: "Onion cc", created_at: DateTime.parse("Tue, 19 Mar 2019 19:55:54 UTC +00:00"), updated_at: DateTime.parse("Tue, 19 Mar 2019 20:14:52 UTC +00:00"), product_id: 14, certcourse_pages_count: 4 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create(  id: 69, long_name: "Cip's quiz answer page is in a future page", short_name: "Cips back page is in the future", description: "The quiz in this course is in a future page", color_hex: "#000000", status: "live", duration: 0, is_completed: false, copyright_text: "The quiz in this course is in a future page", created_at: DateTime.parse("Thu, 04 Apr 2019 14:58:45 UTC +00:00"), updated_at: DateTime.parse("Fri, 05 Apr 2019 17:01:27 UTC +00:00"), product_id: 14, certcourse_pages_count: 5 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 65, long_name: "Cip's stuff one stuff too many", short_name: "Cip's one stuff too many", description: "this course will teach you how to nothing. Have fun", color_hex: "#000000", status: "live", duration: 2, is_completed: false, copyright_text: "Go away copyright breaker", created_at: DateTime.parse("Wed, 20 Mar 2019 14:20:59 UTC +00:00"), updated_at: DateTime.parse("Wed, 20 Mar 2019 17:00:59 UTC +00:00"), product_id: 14, certcourse_pages_count: 10 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 70, long_name: "Cips 2 page image course", short_name: "cips 2 page image", description: "this course has 2 pages images, ", color_hex: "#f243e6", status: "live", duration: 1, is_completed: false, copyright_text: "go fish", created_at: DateTime.parse("Tue, 16 Apr 2019 13:36:19 UTC +00:00"), updated_at: DateTime.parse("Tue, 16 Apr 2019 13:46:55 UTC +00:00"), product_id: 14, certcourse_pages_count: 2 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 66, long_name: "Cips one page course that has 2 pages ", short_name: "Cips 1page 2 page course", description: "Error - cannot retrieve data from portal", color_hex: "#000000", status: "live", duration: 1, is_completed: false, copyright_text: "what is this text doing here, hovering", created_at: DateTime.parse("Fri, 22 Mar 2019 15:26:50 UTC +00:00"), updated_at: DateTime.parse("Fri, 22 Mar 2019 15:34:44 UTC +00:00"), product_id: 14, certcourse_pages_count: 2 ) rescue ActiveRecord::ActiveRecordError
Certcourse.create( id: 71, long_name: "Cips 2 page video course", short_name: "cips 2 page videos", description: "this course has 2 pages, videos", color_hex: "#f243e6", status: "live", duration: 1, is_completed: false, copyright_text: "Show me the copy", created_at: DateTime.parse("Tue, 16 Apr 2019 13:37:13 UTC +00:00"), updated_at: DateTime.parse("Tue, 16 Apr 2019 13:47:11 UTC +00:00"), product_id: 14, certcourse_pages_count: 2 ) rescue ActiveRecord::ActiveRecordError
