CertificateCertcourse.create!(
  [{ id: 2,
    certificate_id: 1,
    certcourse_id: 2,
    certcourse_order: 2,
    product_id: 14 },
   { id: 3,
    certificate_id: 3,
    certcourse_id: 3,
    certcourse_order: 1,
    product_id: 14 },
   { id: 4,
    certificate_id: 3,
    certcourse_id: 4,
    certcourse_order: 2,
    product_id: 14 },
   { id: 5,
    certificate_id: 4,
    certcourse_id: 5,
    certcourse_order: 1,
    product_id: 14 },
   { id: 6,
    certificate_id: 5,
    certcourse_id: 6,
    certcourse_order: 1,
    product_id: 14 },
   { id: 7,
    certificate_id: 6,
    certcourse_id: 7,
    certcourse_order: 1,
    product_id: 14 },
   { id: 9,
    certificate_id: 7,
    certcourse_id: 8,
    certcourse_order: 1,
    product_id: 14 },
   { id: 10,
    certificate_id: 7,
    certcourse_id: 9,
    certcourse_order: 2,
    product_id: 14 },
   { id: 11,
    certificate_id: 7,
    certcourse_id: 10,
    certcourse_order: 3,
    product_id: 14 },
   { id: 12,
    certificate_id: 7,
    certcourse_id: 11,
    certcourse_order: 4,
    product_id: 14 },
   { id: 13,
    certificate_id: 7,
    certcourse_id: 12,
    certcourse_order: 5,
    product_id: 14 },
   { id: 14,
    certificate_id: 7,
    certcourse_id: 13,
    certcourse_order: 6,
    product_id: 14 },
   { id: 15,
    certificate_id: 7,
    certcourse_id: 14,
    certcourse_order: 7,
    product_id: 14 },
   { id: 16,
    certificate_id: 7,
    certcourse_id: 15,
    certcourse_order: 8,
    product_id: 14 },
   { id: 17,
    certificate_id: 7,
    certcourse_id: 16,
    certcourse_order: 9,
    product_id: 14 },
   { id: 18,
    certificate_id: 7,
    certcourse_id: 17,
    certcourse_order: 10,
    product_id: 14 },
   { id: 19,
    certificate_id: 7,
    certcourse_id: 18,
    certcourse_order: 11,
    product_id: 14 },
   { id: 20,
    certificate_id: 7,
    certcourse_id: 19,
    certcourse_order: 12,
    product_id: 14 },
   { id: 1,
    certificate_id: 1,
    certcourse_id: 1,
    certcourse_order: 3,
    product_id: 14 },
   { id: 21,
    certificate_id: 8,
    certcourse_id: 21,
    certcourse_order: 1,
    product_id: 15 },
   { id: 22,
    certificate_id: 9,
    certcourse_id: 22,
    certcourse_order: 3,
    product_id: 14 },
   { id: 55,
    certificate_id: 44,
    certcourse_id: 59,
    certcourse_order: 3,
    product_id: 14 },
   { id: 56,
    certificate_id: 45,
    certcourse_id: 60,
    certcourse_order: 5,
    product_id: 14 },
   { id: 57,
    certificate_id: 44,
    certcourse_id: 61,
    certcourse_order: 2,
    product_id: 14 },
   { id: 58,
    certificate_id: 46,
    certcourse_id: 62,
    certcourse_order: 3,
    product_id: 14 },
   { id: 59,
    certificate_id: 47,
    certcourse_id: 63,
    certcourse_order: 1,
    product_id: 14 },
   { id: 60,
    certificate_id: 48,
    certcourse_id: 64,
    certcourse_order: 1,
    product_id: 14 },
   { id: 61,
    certificate_id: 49,
    certcourse_id: 65,
    certcourse_order: 5,
    product_id: 14 },
   { id: 63,
    certificate_id: 46,
    certcourse_id: 66,
    certcourse_order: 2,
    product_id: 14 },
   { id: 64,
    certificate_id: 50,
    certcourse_id: 67,
    certcourse_order: 1,
    product_id: 14 },
   { id: 65,
    certificate_id: 50,
    certcourse_id: 68,
    certcourse_order: 2,
    product_id: 14 },
   { id: 66,
    certificate_id: 50,
    certcourse_id: 69,
    certcourse_order: 3,
    product_id: 14 },
   { id: 67,
    certificate_id: 51,
    certcourse_id: 70,
    certcourse_order: 1,
    product_id: 14 },
   { id: 68,
    certificate_id: 51,
    certcourse_id: 71,
    certcourse_order: 2,
    product_id: 14 },
   { id: 69,
    certificate_id: 52,
    certcourse_id: 62,
    certcourse_order: 1,
    product_id: 14 },
   { id: 70,
    certificate_id: 52,
    certcourse_id: 59,
    certcourse_order: 2,
    product_id: 14 },
   { id: 71,
    certificate_id: 53,
    certcourse_id: 62,
    certcourse_order: 1,
    product_id: 14 },
   { id: 72,
    certificate_id: 53,
    certcourse_id: 59,
    certcourse_order: 2,
    product_id: 14 },
   { id: 73,
    certificate_id: 53,
    certcourse_id: 61,
    certcourse_order: 3,
    product_id: 14 },
   { id: 74,
    certificate_id: 50,
    certcourse_id: 72,
    certcourse_order: 4,
    product_id: 14 },
   { id: 75,
    certificate_id: 55,
    certcourse_id: 74,
    certcourse_order: 1,
    product_id: 14 }]

)
