CertcoursePage.create!(
  [{ id: 1,
    certcourse_id: 1,
    certcourse_page_order: 1,
    duration: 20,
    background_color_hex: "#000000",
    content_type: nil,
    product_id: 14 },
   { id: 2,
    certcourse_id: 1,
    certcourse_page_order: 2,
    duration: 60,
    background_color_hex: "#000000",
    content_type: nil,
    product_id: 14 },
   { id: 3,
    certcourse_id: 1,
    certcourse_page_order: 3,
    duration: 45,
    background_color_hex: "#000000",
    content_type: nil,
    product_id: 14 },
   { id: 5,
    certcourse_id: 1,
    certcourse_page_order: 4,
    duration: 60,
    background_color_hex: "#000000",
    content_type: nil,
    product_id: 14 },
   { id: 6,
    certcourse_id: 1,
    certcourse_page_order: 5,
    duration: 60,
    background_color_hex: "#000000",
    content_type: nil,
    product_id: 14 },
   { id: 7,
    certcourse_id: 1,
    certcourse_page_order: 6,
    duration: 30,
    background_color_hex: "#000000",
    content_type: nil,
    product_id: 14 },
   { id: 8,
    certcourse_id: 5,
    certcourse_page_order: 1,
    duration: 33,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 9,
    certcourse_id: 5,
    certcourse_page_order: 2,
    duration: 20,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 13,
    certcourse_id: 5,
    certcourse_page_order: 6,
    duration: 19,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 10,
    certcourse_id: 5,
    certcourse_page_order: 3,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 11,
    certcourse_id: 5,
    certcourse_page_order: 4,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 12,
    certcourse_id: 5,
    certcourse_page_order: 5,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 39,
    certcourse_id: 5,
    certcourse_page_order: 32,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 14,
    certcourse_id: 5,
    certcourse_page_order: 7,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 15,
    certcourse_id: 5,
    certcourse_page_order: 8,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 16,
    certcourse_id: 5,
    certcourse_page_order: 9,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 18,
    certcourse_id: 5,
    certcourse_page_order: 11,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 19,
    certcourse_id: 5,
    certcourse_page_order: 12,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 20,
    certcourse_id: 5,
    certcourse_page_order: 13,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 21,
    certcourse_id: 5,
    certcourse_page_order: 14,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 17,
    certcourse_id: 5,
    certcourse_page_order: 10,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 22,
    certcourse_id: 5,
    certcourse_page_order: 15,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 40,
    certcourse_id: 5,
    certcourse_page_order: 33,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 41,
    certcourse_id: 5,
    certcourse_page_order: 34,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 42,
    certcourse_id: 5,
    certcourse_page_order: 35,
    duration: 31,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 24,
    certcourse_id: 5,
    certcourse_page_order: 17,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 23,
    certcourse_id: 5,
    certcourse_page_order: 16,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 43,
    certcourse_id: 5,
    certcourse_page_order: 36,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 25,
    certcourse_id: 5,
    certcourse_page_order: 18,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 26,
    certcourse_id: 5,
    certcourse_page_order: 19,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 27,
    certcourse_id: 5,
    certcourse_page_order: 20,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 44,
    certcourse_id: 5,
    certcourse_page_order: 37,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 46,
    certcourse_id: 5,
    certcourse_page_order: 39,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 45,
    certcourse_id: 5,
    certcourse_page_order: 38,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 36,
    certcourse_id: 5,
    certcourse_page_order: 29,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 38,
    certcourse_id: 5,
    certcourse_page_order: 31,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 84,
    certcourse_id: 6,
    certcourse_page_order: 27,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 85,
    certcourse_id: 6,
    certcourse_page_order: 28,
    duration: 22,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 28,
    certcourse_id: 5,
    certcourse_page_order: 21,
    duration: 13,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 29,
    certcourse_id: 5,
    certcourse_page_order: 22,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 30,
    certcourse_id: 5,
    certcourse_page_order: 23,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 31,
    certcourse_id: 5,
    certcourse_page_order: 24,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 32,
    certcourse_id: 5,
    certcourse_page_order: 25,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 33,
    certcourse_id: 5,
    certcourse_page_order: 26,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 34,
    certcourse_id: 5,
    certcourse_page_order: 27,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 35,
    certcourse_id: 5,
    certcourse_page_order: 28,
    duration: 22,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 37,
    certcourse_id: 5,
    certcourse_page_order: 30,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 51,
    certcourse_id: 6,
    certcourse_page_order: 3,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 52,
    certcourse_id: 6,
    certcourse_page_order: 4,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 53,
    certcourse_id: 6,
    certcourse_page_order: 5,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 54,
    certcourse_id: 6,
    certcourse_page_order: 32,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 55,
    certcourse_id: 6,
    certcourse_page_order: 7,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 56,
    certcourse_id: 6,
    certcourse_page_order: 8,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 57,
    certcourse_id: 6,
    certcourse_page_order: 9,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 58,
    certcourse_id: 6,
    certcourse_page_order: 11,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 59,
    certcourse_id: 6,
    certcourse_page_order: 12,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 63,
    certcourse_id: 6,
    certcourse_page_order: 15,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 64,
    certcourse_id: 6,
    certcourse_page_order: 33,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 65,
    certcourse_id: 6,
    certcourse_page_order: 34,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 66,
    certcourse_id: 6,
    certcourse_page_order: 35,
    duration: 31,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 71,
    certcourse_id: 6,
    certcourse_page_order: 19,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 72,
    certcourse_id: 6,
    certcourse_page_order: 20,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 73,
    certcourse_id: 6,
    certcourse_page_order: 37,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 74,
    certcourse_id: 6,
    certcourse_page_order: 39,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 78,
    certcourse_id: 6,
    certcourse_page_order: 21,
    duration: 13,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 80,
    certcourse_id: 6,
    certcourse_page_order: 23,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 81,
    certcourse_id: 6,
    certcourse_page_order: 24,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 82,
    certcourse_id: 6,
    certcourse_page_order: 25,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 60,
    certcourse_id: 6,
    certcourse_page_order: 13,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 68,
    certcourse_id: 6,
    certcourse_page_order: 16,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 76,
    certcourse_id: 6,
    certcourse_page_order: 29,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 79,
    certcourse_id: 6,
    certcourse_page_order: 22,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 83,
    certcourse_id: 6,
    certcourse_page_order: 26,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 48,
    certcourse_id: 6,
    certcourse_page_order: 1,
    duration: 33,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 49,
    certcourse_id: 6,
    certcourse_page_order: 2,
    duration: 20,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 50,
    certcourse_id: 6,
    certcourse_page_order: 6,
    duration: 19,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 62,
    certcourse_id: 6,
    certcourse_page_order: 10,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 67,
    certcourse_id: 6,
    certcourse_page_order: 17,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 75,
    certcourse_id: 6,
    certcourse_page_order: 38,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 77,
    certcourse_id: 6,
    certcourse_page_order: 31,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 86,
    certcourse_id: 6,
    certcourse_page_order: 30,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 61,
    certcourse_id: 6,
    certcourse_page_order: 14,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 69,
    certcourse_id: 6,
    certcourse_page_order: 36,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 70,
    certcourse_id: 6,
    certcourse_page_order: 18,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 87,
    certcourse_id: 7,
    certcourse_page_order: 1,
    duration: 33,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 88,
    certcourse_id: 7,
    certcourse_page_order: 2,
    duration: 20,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 89,
    certcourse_id: 7,
    certcourse_page_order: 3,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 90,
    certcourse_id: 7,
    certcourse_page_order: 4,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 91,
    certcourse_id: 7,
    certcourse_page_order: 5,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 92,
    certcourse_id: 7,
    certcourse_page_order: 6,
    duration: 19,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 93,
    certcourse_id: 7,
    certcourse_page_order: 7,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 94,
    certcourse_id: 7,
    certcourse_page_order: 8,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 95,
    certcourse_id: 7,
    certcourse_page_order: 9,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 96,
    certcourse_id: 7,
    certcourse_page_order: 10,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 97,
    certcourse_id: 7,
    certcourse_page_order: 11,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 98,
    certcourse_id: 7,
    certcourse_page_order: 12,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 99,
    certcourse_id: 7,
    certcourse_page_order: 13,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 100,
    certcourse_id: 7,
    certcourse_page_order: 14,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 101,
    certcourse_id: 7,
    certcourse_page_order: 15,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 102,
    certcourse_id: 7,
    certcourse_page_order: 16,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 103,
    certcourse_id: 7,
    certcourse_page_order: 17,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 104,
    certcourse_id: 7,
    certcourse_page_order: 18,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 105,
    certcourse_id: 7,
    certcourse_page_order: 19,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 106,
    certcourse_id: 7,
    certcourse_page_order: 20,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 107,
    certcourse_id: 7,
    certcourse_page_order: 21,
    duration: 13,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 108,
    certcourse_id: 7,
    certcourse_page_order: 22,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 109,
    certcourse_id: 7,
    certcourse_page_order: 23,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 110,
    certcourse_id: 7,
    certcourse_page_order: 24,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 111,
    certcourse_id: 7,
    certcourse_page_order: 25,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 112,
    certcourse_id: 7,
    certcourse_page_order: 26,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 113,
    certcourse_id: 7,
    certcourse_page_order: 27,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 114,
    certcourse_id: 7,
    certcourse_page_order: 28,
    duration: 22,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 115,
    certcourse_id: 7,
    certcourse_page_order: 29,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 116,
    certcourse_id: 7,
    certcourse_page_order: 30,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 118,
    certcourse_id: 7,
    certcourse_page_order: 32,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 119,
    certcourse_id: 7,
    certcourse_page_order: 33,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 120,
    certcourse_id: 7,
    certcourse_page_order: 34,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 121,
    certcourse_id: 7,
    certcourse_page_order: 35,
    duration: 31,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 122,
    certcourse_id: 7,
    certcourse_page_order: 36,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 123,
    certcourse_id: 7,
    certcourse_page_order: 37,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 124,
    certcourse_id: 7,
    certcourse_page_order: 38,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 125,
    certcourse_id: 7,
    certcourse_page_order: 39,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 117,
    certcourse_id: 7,
    certcourse_page_order: 31,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 127,
    certcourse_id: 8,
    certcourse_page_order: 2,
    duration: 5,
    background_color_hex: "#ffa500",
    content_type: "image",
    product_id: 14 },
   { id: 128,
    certcourse_id: 8,
    certcourse_page_order: 3,
    duration: 15,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 126,
    certcourse_id: 8,
    certcourse_page_order: 1,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 132,
    certcourse_id: 21,
    certcourse_page_order: 3,
    duration: 6,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 15 },
   { id: 130,
    certcourse_id: 21,
    certcourse_page_order: 1,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 15 },
   { id: 131,
    certcourse_id: 21,
    certcourse_page_order: 2,
    duration: 7,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 15 },
   { id: 133,
    certcourse_id: 22,
    certcourse_page_order: 1,
    duration: 5,
    background_color_hex: "#b83939",
    content_type: "image",
    product_id: 14 },
   { id: 135,
    certcourse_id: 22,
    certcourse_page_order: 3,
    duration: 7,
    background_color_hex: "#b83939",
    content_type: "video",
    product_id: 14 },
   { id: 136,
    certcourse_id: 22,
    certcourse_page_order: 4,
    duration: 6,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 137,
    certcourse_id: 22,
    certcourse_page_order: 5,
    duration: 9,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 134,
    certcourse_id: 22,
    certcourse_page_order: 2,
    duration: 5,
    background_color_hex: "#b83939",
    content_type: "image",
    product_id: 14 },
   { id: 129,
    certcourse_id: 20,
    certcourse_page_order: 1,
    duration: 56,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 195,
    certcourse_id: 1,
    certcourse_page_order: 5000,
    duration: 0,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 196,
    certcourse_id: 59,
    certcourse_page_order: 1,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 197,
    certcourse_id: 59,
    certcourse_page_order: 2,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 199,
    certcourse_id: 59,
    certcourse_page_order: 3,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 198,
    certcourse_id: 59,
    certcourse_page_order: 4,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 224,
    certcourse_id: 62,
    certcourse_page_order: 2,
    duration: 18,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 210,
    certcourse_id: 61,
    certcourse_page_order: 5,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 200,
    certcourse_id: 60,
    certcourse_page_order: 1,
    duration: 6,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 202,
    certcourse_id: 60,
    certcourse_page_order: 3,
    duration: 20,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 203,
    certcourse_id: 60,
    certcourse_page_order: 4,
    duration: 20,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 205,
    certcourse_id: 60,
    certcourse_page_order: 5,
    duration: 20,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 207,
    certcourse_id: 60,
    certcourse_page_order: 6,
    duration: 20,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 204,
    certcourse_id: 61,
    certcourse_page_order: 1,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 213,
    certcourse_id: 60,
    certcourse_page_order: 7,
    duration: 20,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 206,
    certcourse_id: 61,
    certcourse_page_order: 2,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 208,
    certcourse_id: 61,
    certcourse_page_order: 3,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 209,
    certcourse_id: 61,
    certcourse_page_order: 4,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 215,
    certcourse_id: 61,
    certcourse_page_order: 7,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 216,
    certcourse_id: 61,
    certcourse_page_order: 8,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 217,
    certcourse_id: 61,
    certcourse_page_order: 9,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 211,
    certcourse_id: 61,
    certcourse_page_order: 6,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 222,
    certcourse_id: 60,
    certcourse_page_order: 8,
    duration: 20,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 218,
    certcourse_id: 61,
    certcourse_page_order: 10,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 219,
    certcourse_id: 61,
    certcourse_page_order: 11,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 220,
    certcourse_id: 61,
    certcourse_page_order: 12,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 212,
    certcourse_id: 61,
    certcourse_page_order: 14,
    duration: 3,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 221,
    certcourse_id: 61,
    certcourse_page_order: 13,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 226,
    certcourse_id: 62,
    certcourse_page_order: 4,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 225,
    certcourse_id: 62,
    certcourse_page_order: 3,
    duration: 43,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 227,
    certcourse_id: 62,
    certcourse_page_order: 5,
    duration: 12,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 228,
    certcourse_id: 62,
    certcourse_page_order: 6,
    duration: 32,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 231,
    certcourse_id: 62,
    certcourse_page_order: 9,
    duration: 16,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 232,
    certcourse_id: 62,
    certcourse_page_order: 10,
    duration: 49,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 229,
    certcourse_id: 62,
    certcourse_page_order: 7,
    duration: 60,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 230,
    certcourse_id: 62,
    certcourse_page_order: 8,
    duration: 60,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 201,
    certcourse_id: 60,
    certcourse_page_order: 2,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 233,
    certcourse_id: 62,
    certcourse_page_order: 11,
    duration: 17,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 234,
    certcourse_id: 62,
    certcourse_page_order: 12,
    duration: 25,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 235,
    certcourse_id: 62,
    certcourse_page_order: 13,
    duration: 23,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 237,
    certcourse_id: 62,
    certcourse_page_order: 15,
    duration: 44,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 236,
    certcourse_id: 62,
    certcourse_page_order: 14,
    duration: 60,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 269,
    certcourse_id: 69,
    certcourse_page_order: 1,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 270,
    certcourse_id: 69,
    certcourse_page_order: 2,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 239,
    certcourse_id: 63,
    certcourse_page_order: 1,
    duration: 4,
    background_color_hex: "#1c444f",
    content_type: "image",
    product_id: 14 },
   { id: 240,
    certcourse_id: 63,
    certcourse_page_order: 2,
    duration: 4,
    background_color_hex: "#1c444f",
    content_type: "video",
    product_id: 14 },
   { id: 271,
    certcourse_id: 69,
    certcourse_page_order: 3,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 268,
    certcourse_id: 68,
    certcourse_page_order: 2,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 242,
    certcourse_id: 63,
    certcourse_page_order: 4,
    duration: 30,
    background_color_hex: "#1c444f",
    content_type: "quiz",
    product_id: 14 },
   { id: 267,
    certcourse_id: 68,
    certcourse_page_order: 1,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 244,
    certcourse_id: 64,
    certcourse_page_order: 1,
    duration: 5,
    background_color_hex: "#2185ef",
    content_type: "image",
    product_id: 14 },
   { id: 245,
    certcourse_id: 64,
    certcourse_page_order: 2,
    duration: 5,
    background_color_hex: "#3cb201",
    content_type: "video",
    product_id: 14 },
   { id: 246,
    certcourse_id: 64,
    certcourse_page_order: 3,
    duration: 10,
    background_color_hex: "#b21601",
    content_type: "quiz",
    product_id: 14 },
   { id: 243,
    certcourse_id: 64,
    certcourse_page_order: 4,
    duration: 5,
    background_color_hex: "#a2eef2",
    content_type: "image",
    product_id: 14 },
   { id: 247,
    certcourse_id: 60,
    certcourse_page_order: 9,
    duration: 5,
    background_color_hex: "#FF8C00",
    content_type: "image",
    product_id: 14 },
   { id: 274,
    certcourse_id: 20,
    certcourse_page_order: 333,
    duration: 0,
    background_color_hex: "#000000",
    content_type: nil,
    product_id: 14 },
   { id: 223,
    certcourse_id: 62,
    certcourse_page_order: 1,
    duration: 23,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 272,
    certcourse_id: 69,
    certcourse_page_order: 4,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 249,
    certcourse_id: 60,
    certcourse_page_order: 10,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 273,
    certcourse_id: 69,
    certcourse_page_order: 5,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 238,
    certcourse_id: 62,
    certcourse_page_order: 17,
    duration: 15,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 248,
    certcourse_id: 62,
    certcourse_page_order: 16,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 250,
    certcourse_id: 60,
    certcourse_page_order: 11,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 251,
    certcourse_id: 65,
    certcourse_page_order: 1,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 252,
    certcourse_id: 65,
    certcourse_page_order: 2,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 253,
    certcourse_id: 65,
    certcourse_page_order: 3,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 254,
    certcourse_id: 65,
    certcourse_page_order: 4,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 255,
    certcourse_id: 65,
    certcourse_page_order: 5,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 256,
    certcourse_id: 65,
    certcourse_page_order: 6,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 257,
    certcourse_id: 65,
    certcourse_page_order: 7,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 258,
    certcourse_id: 65,
    certcourse_page_order: 8,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 260,
    certcourse_id: 65,
    certcourse_page_order: 9,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 261,
    certcourse_id: 65,
    certcourse_page_order: 10,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 262,
    certcourse_id: 66,
    certcourse_page_order: 1,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 263,
    certcourse_id: 66,
    certcourse_page_order: 2,
    duration: 5,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 241,
    certcourse_id: 63,
    certcourse_page_order: 3,
    duration: 10,
    background_color_hex: "#1c444f",
    content_type: "quiz",
    product_id: 14 },
   { id: 264,
    certcourse_id: 67,
    certcourse_page_order: 1,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 265,
    certcourse_id: 67,
    certcourse_page_order: 2,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 266,
    certcourse_id: 67,
    certcourse_page_order: 3,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 286,
    certcourse_id: 74,
    certcourse_page_order: 3,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 287,
    certcourse_id: 74,
    certcourse_page_order: 4,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 275,
    certcourse_id: 70,
    certcourse_page_order: 1,
    duration: 15,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 276,
    certcourse_id: 70,
    certcourse_page_order: 2,
    duration: 15,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 277,
    certcourse_id: 71,
    certcourse_page_order: 1,
    duration: 15,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 278,
    certcourse_id: 71,
    certcourse_page_order: 2,
    duration: 15,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 279,
    certcourse_id: 72,
    certcourse_page_order: 1,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 280,
    certcourse_id: 72,
    certcourse_page_order: 2,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 281,
    certcourse_id: 73,
    certcourse_page_order: 0,
    duration: 0,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 282,
    certcourse_id: 73,
    certcourse_page_order: 1,
    duration: 0,
    background_color_hex: "#000000",
    content_type: nil,
    product_id: 14 },
   { id: 283,
    certcourse_id: 74,
    certcourse_page_order: 0,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 284,
    certcourse_id: 74,
    certcourse_page_order: 1,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "video",
    product_id: 14 },
   { id: 285,
    certcourse_id: 74,
    certcourse_page_order: 2,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 288,
    certcourse_id: 74,
    certcourse_page_order: 5,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 289,
    certcourse_id: 74,
    certcourse_page_order: 6,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 290,
    certcourse_id: 74,
    certcourse_page_order: 7,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 291,
    certcourse_id: 74,
    certcourse_page_order: 8,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "quiz",
    product_id: 14 },
   { id: 292,
    certcourse_id: 74,
    certcourse_page_order: 9,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 293,
    certcourse_id: 74,
    certcourse_page_order: 10,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 294,
    certcourse_id: 74,
    certcourse_page_order: 11,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 },
   { id: 295,
    certcourse_id: 74,
    certcourse_page_order: 12,
    duration: 10,
    background_color_hex: "#000000",
    content_type: "image",
    product_id: 14 }])
