QuizPage.create!(
  [{ id: 1,
    certcourse_page_id: 1,
    is_optional: true,
    quiz_text: "Why did the kitchen cross the road ?",
    wrong_answer_page_id: nil,
    product_id: 14 },
   { id: 2,
    certcourse_page_id: 2,
    is_optional: true,
    quiz_text: "What's the biggest number ?",
    wrong_answer_page_id: nil,
    product_id: 14 },
   { id: 3,
    certcourse_page_id: 3,
    is_optional: false,
    quiz_text: "Trick question ?",
    wrong_answer_page_id: 1,
    product_id: 14 },
   { id: 5,
    certcourse_page_id: 17,
    is_optional: false,
    quiz_text:       "Which form of identification is acceptable for entrance to the facility",
    wrong_answer_page_id: 15,
    product_id: 14 },
   { id: 6,
    certcourse_page_id: 23,
    is_optional: false,
    quiz_text: "Who will I never let into a Medical Cannabis Dispensary",
    wrong_answer_page_id: 18,
    product_id: 14 },
   { id: 7,
    certcourse_page_id: 36,
    is_optional: true,
    quiz_text: "What are the current purchase limits for consumers ?",
    wrong_answer_page_id: nil,
    product_id: 14 },
   { id: 8,
    certcourse_page_id: 38,
    is_optional: false,
    quiz_text: "When driving with cannabis, which statement is true ?",
    wrong_answer_page_id: 37,
    product_id: 14 },
   { id: 9,
    certcourse_page_id: 86,
    is_optional: false,
    quiz_text:       "What is the requirement for entrance to a recreational dispensary ?",
    wrong_answer_page_id: 10,
    product_id: 14 },
   { id: 10,
    certcourse_page_id: 55,
    is_optional: false,
    quiz_text:       "Which form of identification is acceptable for entrance to the facility",
    wrong_answer_page_id: 15,
    product_id: 14 },
   { id: 11,
    certcourse_page_id: 61,
    is_optional: false,
    quiz_text: "Who will I never let into a Medical Cannabis Dispensary",
    wrong_answer_page_id: 18,
    product_id: 14 },
   { id: 12,
    certcourse_page_id: 69,
    is_optional: true,
    quiz_text: "What are the current purchase limits for consumers ?",
    wrong_answer_page_id: nil,
    product_id: 14 },
   { id: 13,
    certcourse_page_id: 70,
    is_optional: false,
    quiz_text: "When driving with cannabis, which statement is true ?",
    wrong_answer_page_id: 37,
    product_id: 14 },
   { id: 4,
    certcourse_page_id: 14,
    is_optional: false,
    quiz_text:       "What is the requirement for entrance to a recreational dispensary ?",
    wrong_answer_page_id: 10,
    product_id: 14 },
   { id: 14,
    certcourse_page_id: 93,
    is_optional: false,
    quiz_text:       "What is the requirement for entrance to a recreational dispensary ?",
    wrong_answer_page_id: 90,
    product_id: 14 },
   { id: 15,
    certcourse_page_id: 96,
    is_optional: false,
    quiz_text:       "Which form of identification is acceptable for entrance to the facility",
    wrong_answer_page_id: 94,
    product_id: 14 },
   { id: 16,
    certcourse_page_id: 102,
    is_optional: false,
    quiz_text: "Who will I never let into a Medical Cannabis Dispensary",
    wrong_answer_page_id: 100,
    product_id: 14 },
   { id: 17,
    certcourse_page_id: 115,
    is_optional: true,
    quiz_text: "What are the current purchase limits for consumers ?",
    wrong_answer_page_id: 112,
    product_id: 14 },
   { id: 18,
    certcourse_page_id: 117,
    is_optional: false,
    quiz_text: "When driving with cannabis, which statement is true ?",
    wrong_answer_page_id: 116,
    product_id: 14 },
   { id: 19,
    certcourse_page_id: 128,
    is_optional: false,
    quiz_text: "Did you like the quiz?",
    wrong_answer_page_id: 127,
    product_id: 14 },
   { id: 20,
    certcourse_page_id: 132,
    is_optional: false,
    quiz_text: "Do you like the new app?",
    wrong_answer_page_id: 1,
    product_id: 15 },
   { id: 21,
    certcourse_page_id: 136,
    is_optional: true,
    quiz_text: "How are you?",
    wrong_answer_page_id: 2,
    product_id: 14 },
   { id: 54,
    certcourse_page_id: 198,
    is_optional: true,
    quiz_text: "how bout that",
    wrong_answer_page_id: nil,
    product_id: 14 },
   { id: 56,
    certcourse_page_id: 221,
    is_optional: false,
    quiz_text: "Useful isn't it?",
    wrong_answer_page_id: 220,
    product_id: 14 },
   { id: 57,
    certcourse_page_id: 222,
    is_optional: false,
    quiz_text: "Care-i diferenta dintre balaur si dragon ? ",
    wrong_answer_page_id: 1,
    product_id: 14 },
   { id: 55,
    certcourse_page_id: 213,
    is_optional: false,
    quiz_text: "Cine a infipt laleaua in branza? ",
    wrong_answer_page_id: nil,
    product_id: 14 },
   { id: 58,
    certcourse_page_id: 229,
    is_optional: false,
    quiz_text: "Why did the chicken cross the road",
    wrong_answer_page_id: 227,
    product_id: 14 },
   { id: 59,
    certcourse_page_id: 230,
    is_optional: false,
    quiz_text: "Who stabbed the window?",
    wrong_answer_page_id: 228,
    product_id: 14 },
   { id: 60,
    certcourse_page_id: 236,
    is_optional: false,
    quiz_text: "Doi scheleti se trag de piele, de ce?",
    wrong_answer_page_id: 235,
    product_id: 14 },
   { id: 61,
    certcourse_page_id: 241,
    is_optional: true,
    quiz_text: "Onions are sweet?",
    wrong_answer_page_id: nil,
    product_id: 14 },
   { id: 63,
    certcourse_page_id: 246,
    is_optional: false,
    quiz_text: "Milk lover? Si o No?",
    wrong_answer_page_id: 243,
    product_id: 14 },
   { id: 62,
    certcourse_page_id: 242,
    is_optional: false,
    quiz_text: "Do you like eggs?",
    wrong_answer_page_id: 239,
    product_id: 14 },
   { id: 66,
    certcourse_page_id: 265,
    is_optional: false,
    quiz_text: "Red or blue?",
    wrong_answer_page_id: 264,
    product_id: 14 },
   { id: 68,
    certcourse_page_id: 270,
    is_optional: false,
    quiz_text: "The back page is in the future. id272",
    wrong_answer_page_id: 272,
    product_id: 14 },
   { id: 69,
    certcourse_page_id: 280,
    is_optional: false,
    quiz_text: "Is the wrong answer of this quiz on a wrong page?",
    wrong_answer_page_id: nil,
    product_id: 14 },
   { id: 70,
    certcourse_page_id: 281,
    is_optional: false,
    quiz_text: "",
    wrong_answer_page_id: nil,
    product_id: 14 },
   { id: 64,
    certcourse_page_id: 249,
    is_optional: true,
    quiz_text: "Liberare ori moarte striga toti !? ",
    wrong_answer_page_id: 1,
    product_id: 14 },
   { id: 67,
    certcourse_page_id: 268,
    is_optional: true,
    quiz_text: "Optional quiz with wrong answer page",
    wrong_answer_page_id: 267,
    product_id: 14 },
   { id: 65,
    certcourse_page_id: 250,
    is_optional: false,
    quiz_text: "Cat faci pana la Gara ca sa schimbi ora ?",
    wrong_answer_page_id: 250,
    product_id: 14 },
   { id: 71,
    certcourse_page_id: 291,
    is_optional: true,
    quiz_text:       "The wrong answer on this optional quiz has a wrong answer page id",
    wrong_answer_page_id: 286,
    product_id: 14 }])
