
build:initial:
  extends: .base
  stage: build
  script:
    - echo "main"

build:assets_precompile:
  extends: .base_db
  stage: build
  script:
    - rm -r tmp/cache/
    - bundle exec rake assets:precompile
