# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

shared: &shared
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  aws_transcoder_key: <%= ENV["AWS_TRANSCODER_KEY"] %>
  aws_transcoder_secret: <%= ENV["AWS_TRANSCODER_SECRET"] %>
  aws_pipeline_id: <%= ENV["AWS_PIPELINE_ID"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  paperclip_secret: <%= ENV["PAPERCLIP_SECRET"] %>

  hls_server: 'http://d9f7ufze0iovw.cloudfront.net/'
  rtmp_server: "rtmp://s153hddjp1ltg0.cloudfront.net/"
  transcoder_queue_url: <%= ENV["TRANSCODER_QUEUE_URL"]%>
  redis_url: <%= ENV["REDIS_URL"]%>
  google_places_key: <%= ENV['GOOGLE_PLACES_KEY']%>
  mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  firebase_url: <%= ENV["FIREBASE_URL"] %>
  firebase_cm_key: <%= ENV["FIREBASE_CM_KEY"] %>
  firebase_key: <%= ENV["FIREBASE_KEY"] %>
  database_url: <%= ENV["DATABASE_URL"] %>
  fanlink_pg_database: <%= ENV['FANLINK_PG_DATABASE'] %>
  fanlink_pg_user: <%= ENV["FANLINK_PG_USER"]%>
  fanlink_pg_password: <%= ENV['FANLINK_PG_PASSWORD'] %>
  fanlink_pg_host: <%= ENV["FANLINK_PG_HOST"] %>
  rails_max_threads: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  trivia_engine_url: <%= ENV.fetch("TRIVIA_ENGINE_URL", "https://trivia-staging.fan.link/api/publish_game")%>

  smtp_host: <%= ENV.fetch("SMTP_HOST") %>
  smtp_user_name: <%= ENV.fetch("SMTP_USER_NAME") %>
  smtp_password: <%= ENV.fetch("SMTP_PASSWORD") %>
  smtp_port: <%= ENV.fetch("SMTP_PORT", 587) %>
  smtp_authentication: <%= ENV.fetch("SMTP_AUTHENTICATION") %>
  smtp_domain: <%= ENV.fetch("SMTP_DOMAIN") %>

development:
  <<: *shared

test:
  <<: *shared
  secret_key_base: dba6a777c18b9c808f35e44ce23fc6033f07981a52fb9d87eb40209422ba42191123adcf3148780f595dfa033a66e4c3ca4ddcd7507a4cae7414f911271555dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *shared

staging:
  <<: *shared
