# https://medium.com/kkempin/postgresql-master-slave-replication-on-heroku-with-ruby-on-rails-bf0eb8d69fe
<%
   def slave_db_uri
     @cached_slave_db_uri ||=
       begin
         slave_db_env_key = 'HEROKU_POSTGRESQL_IVORY_URL'
         if slave_db_env_key.present? && ENV[slave_db_env_key]
           URI.parse(ENV[slave_db_env_key])
         end
      end
  end
%>
octopus:
  replicated: true
  fully_replicated: true
  production:
    slave:
      adapter: postgresql
      database: <%= (slave_db_uri.path || "").split("/")[1] %>
      username: <%= slave_db_uri.user %>
      password: "<%= slave_db_uri.password %>"
      host: <%= slave_db_uri.host %>
      port: <%= slave_db_uri.port %>
