
deploy:staging:
  extends: .base
  stage: deploy
  artifacts:
    name: "$CI_JOB_NAME-capistrano-log"
    when: on_failure
    paths:
      - log/capistrano.log
  variables:
    RAILS_ENV: staging
  tags:
    - deploy
  environment:
    name: staging
    url: https://staging.fan.link
  only:
    - staging
  script:
    - bundle exec cap staging deploy

deploy:production:
  extends: .base
  stage: deploy
  when: manual
  artifacts:
    name: "$CI_JOB_NAME-capistrano-log"
    when: on_failure
    paths:
      - log/capistrano.log
  variables:
    RAILS_ENV: production
  tags:
    - deploy
  environment:
    name: production
    url: https://portal.fan.link
  only:
    - tags
  script:
    - bundle exec cap production deploy
