Badge.create!([
  {product_id: 7, name_text_old: "Chat for 60 Minutes", internal_name: "chat_60", action_type_id: 13, action_requirement: 10, point_value: 1000, picture_file_name: "Chat_60_-_Level_1.png", picture_content_type: "image/png", picture_file_size: 41190, picture_updated_at: "2018-02-21 04:47:34", description_text_old: "Be active in a chat room for 60 minutes per day for 10 days.", issued_from: nil, issued_to: nil, name: {"un"=>"Chat for 60 Minutes"}, description: {"un"=>"Be active in a chat room for 60 minutes per day for 10 days."}},
  {product_id: 7, name_text_old: "Chat for 30 Minutes", internal_name: "chat_30", action_type_id: 12, action_requirement: 7, point_value: 250, picture_file_name: "Chat_30_-_Level_1.png", picture_content_type: "image/png", picture_file_size: 41740, picture_updated_at: "2018-02-21 04:47:07", description_text_old: "Be active in a chat room for 30 minutes per day for 7 days.", issued_from: nil, issued_to: nil, name: {"un"=>"Chat for 30 Minutes"}, description: {"un"=>"Be active in a chat room for 30 minutes per day for 7 days."}},
  {product_id: 7, name_text_old: "Chat for 10 Minutes", internal_name: "chat_10_7", action_type_id: 10, action_requirement: 7, point_value: 10, picture_file_name: "Chat_10_-_Level_1.png", picture_content_type: "image/png", picture_file_size: 41116, picture_updated_at: "2018-02-21 04:44:36", description_text_old: "Be active in a chat room for 10 minutes every day for 7 days.", issued_from: nil, issued_to: nil, name: {"un"=>"Chat for 10 Minutes"}, description: {"un"=>"Be active in a chat room for 10 minutes every day for 7 days."}},
  {product_id: 7, name_text_old: "Chat for 10 Minutes for 30D", internal_name: "chat_10_30", action_type_id: 10, action_requirement: 30, point_value: 15, picture_file_name: "Chat_10_-_Level_2.png", picture_content_type: "image/png", picture_file_size: 45002, picture_updated_at: "2018-02-21 04:45:39", description_text_old: "Be active in a chat room for 10 minutes per day for 30 days.", issued_from: nil, issued_to: nil, name: {"un"=>"Chat for 10 Minutes for 30D"}, description: {"un"=>"Be active in a chat room for 10 minutes per day for 30 days."}},
  {product_id: 7, name_text_old: "Chat for 10 Minutes for 90D", internal_name: "chat_10_90", action_type_id: 10, action_requirement: 90, point_value: 20, picture_file_name: "Chat_10_-_Level_3.png", picture_content_type: "image/png", picture_file_size: 33420, picture_updated_at: "2018-02-21 04:46:29", description_text_old: "Be active in a chat room for 10 minutes per day for 60 days.", issued_from: nil, issued_to: nil, name: {"un"=>"Chat for 10 Minutes for 90D"}, description: {"un"=>"Be active in a chat room for 10 minutes per day for 60 days."}},
  {product_id: 7, name_text_old: "Active for 7 Days", internal_name: "daily_activity_7", action_type_id: 5, action_requirement: 7, point_value: 100, picture_file_name: "Login_-_Level_1.png", picture_content_type: "image/png", picture_file_size: 35547, picture_updated_at: "2018-02-21 04:49:59", description_text_old: "Open the app every day for 7 days.", issued_from: nil, issued_to: nil, name: {"un"=>"Active for 7 Days"}, description: {"un"=>"Open the app every day for 7 days."}},
  {product_id: 7, name_text_old: "Active for 30 Days", internal_name: "daily_activity_30", action_type_id: 5, action_requirement: 30, point_value: 250, picture_file_name: "Login_-_Level_2.png", picture_content_type: "image/png", picture_file_size: 38366, picture_updated_at: "2018-02-21 04:50:36", description_text_old: "Open the app every day for 30 days.", issued_from: nil, issued_to: nil, name: {"un"=>"Active for 30 Days"}, description: {"un"=>"Open the app every day for 30 days."}},
  {product_id: 7, name_text_old: "Active for 90 Days", internal_name: "daily_activity_90", action_type_id: 5, action_requirement: 90, point_value: 500, picture_file_name: "Login_-_Level_3.png", picture_content_type: "image/png", picture_file_size: 27687, picture_updated_at: "2018-02-21 04:51:10", description_text_old: "Open the app every day for 90 days.", issued_from: nil, issued_to: nil, name: {"un"=>"Active for 90 Days"}, description: {"un"=>"Open the app every day for 90 days."}},
  {product_id: 7, name_text_old: "Follow 25 People", internal_name: "follow_25", action_type_id: 8, action_requirement: 25, point_value: 25, picture_file_name: "Follow_-_Level_1.png", picture_content_type: "image/png", picture_file_size: 35176, picture_updated_at: "2018-02-21 04:48:11", description_text_old: "To follow a user visit their profile and tap the \"Follow\" icon.", issued_from: nil, issued_to: nil, name: {"un"=>"Follow 25 People"}, description: {"un"=>"To follow a user visit their profile and tap the \"Follow\" icon."}},
  {product_id: 7, name_text_old: "Follow 100 People", internal_name: "follow_100", action_type_id: 8, action_requirement: 100, point_value: 100, picture_file_name: "Follow_-_Level_2.png", picture_content_type: "image/png", picture_file_size: 37862, picture_updated_at: "2018-02-21 04:48:48", description_text_old: "To follow a user visit their profile and tap the \"Follow\" button.", issued_from: nil, issued_to: nil, name: {"un"=>"Follow 100 People"}, description: {"un"=>"To follow a user visit their profile and tap the \"Follow\" button."}},
  {product_id: 7, name_text_old: "Follow 250 People", internal_name: "follow_250", action_type_id: 8, action_requirement: 250, point_value: 250, picture_file_name: "Follow_-_Level_3.png", picture_content_type: "image/png", picture_file_size: 27029, picture_updated_at: "2018-02-21 04:49:20", description_text_old: "To follow a user visit their profile and tap the \"Follow\" button.", issued_from: nil, issued_to: nil, name: {"un"=>"Follow 250 People"}, description: {"un"=>"To follow a user visit their profile and tap the \"Follow\" button."}}
])
