rows = [ {"Game"=>"2",
 "Game Name"=>"Cannabis Worldwide",
 "Round Number"=>"2",
 "Question Order"=>"8",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Cannabis Economics",
 "Question"=>"This is approximately 7 grams of marijuana.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Quarter",
 "Visible Characters"=>"2;4;5"} ,
{"Game"=>"5",
 "Game Name"=>"Celebrities in Cannabis",
 "Round Number"=>"1",
 "Question Order"=>"4",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Celebrities in Cannabis",
 "Question"=>
   "This Cheech and Chong movie was released in 1981 and had the duo selling marijuana out of an ice truck. Name the movie.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Nice Dreams",
 "Visible Characters"=>"2;4;5;10"} ,
{"Game"=>"1",
 "Game Name"=>"Basic Cannabis Trivia",
 "Round Number"=>"1",
 "Question Order"=>"4",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Celebrities in Cannabis",
 "Question"=>"Who sang the song \"I Got 5 On It\"",
 "Number of Answers"=>"1",
 "Answer 1"=>"The Luniz",
 "Visible Characters"=>"2;5;8"} ,
{"Game"=>"6",
 "Game Name"=>"I'm A Smoker, A Midnight Toker",
 "Round Number"=>"2",
 "Question Order"=>"6",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Definitions",
 "Question"=>
   "This slang for marijuana, was also an album by Dr. Dre released in 1992.",
 "Number of Answers"=>"1",
 "Answer 1"=>"The Chronic",
 "Visible Characters"=>"1;6;7"},
{"Game"=>"2",
 "Game Name"=>"Cannabis Worldwide",
 "Round Number"=>"3",
 "Question Order"=>"5",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Definitions",
 "Question"=>"What girl's name is commonly a slang term for marijuana?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Mary Jane",
 "Visible Characters"=>"2;5;8"},
{"Game"=>"9",
 "Game Name"=>"Cannabis Facts",
 "Round Number"=>"3",
 "Question Order"=>"8",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Definitions",
 "Question"=>"What is the name of marijuana rolled up in a cigar?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Blunt",
 "Visible Characters"=>"2;3;5"},
{"Game"=>"1",
 "Game Name"=>"Basic Cannabis Trivia",
 "Round Number"=>"2",
 "Question Order"=>"4",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Definitions",
 "Question"=>
   "The process of removing impurities and unwanted elements from cannabis extract. High-quality distillates often go through this several times to create a finished product.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Refinement",
 "Visible Characters"=>"1;3;7;10"},
{"Game"=>"7",
 "Game Name"=>"Ganja Glory",
 "Round Number"=>"3",
 "Question Order"=>"7",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Growing Cannabis",
 "Question"=>
   "The process of freezing crude oil diluted in solvent to separate plant fats and liquids.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Winterize",
 "Visible Characters"=>"1;3;6"},
{"Game"=>"1",
 "Game Name"=>"Basic Cannabis Trivia",
 "Round Number"=>"3",
 "Question Order"=>"7",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Growing Cannabis",
 "Question"=>
   "All of the crystals that make your buds beautiful and camera ready. These are actually glands that are protecting the plant and producing the highest concentration of THC/CBD in the plant.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Trichomes",
 "Visible Characters"=>"2;4;7"},
{"Game"=>"7",
 "Game Name"=>"Ganja Glory",
 "Round Number"=>"1",
 "Question Order"=>"6",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Growing Cannabis",
 "Question"=>"Cannabis grown in full sun and also referred to as “outdoor.”",
 "Number of Answers"=>"1",
 "Answer 1"=>"Sun Grow",
 "Visible Characters"=>"2;4;7"},
{"Game"=>"1",
 "Game Name"=>"Basic Cannabis Trivia",
 "Round Number"=>"1",
 "Question Order"=>"7",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Hemp and Hemp Products",
 "Question"=>
   "Hemp has lower concentrations of THC and higher concentrations of this.",
 "Number of Answers"=>"1",
 "Answer 1"=>"CBD",
 "Visible Characters"=>nil},
{"Game"=>"2",
 "Game Name"=>"Cannabis Worldwide",
 "Round Number"=>"2",
 "Question Order"=>"9",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Hemp and Hemp Products",
 "Question"=>
   "_______ requires minimal care and can grow in most climates and is usually used for industrial purposes.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Hemp",
 "Visible Characters"=>nil},
{"Game"=>"6",
 "Game Name"=>"I'm A Smoker, A Midnight Toker",
 "Round Number"=>"2",
 "Question Order"=>"7",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Hemp and Hemp Products",
 "Question"=>
   "This is a term for a marijuana product that can be either be food or drink.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Derived from Latin",
 "Visible Characters"=>"1;3;8;9;11;15"},
{"Game"=>"1",
 "Game Name"=>"Basic Cannabis Trivia",
 "Round Number"=>"2",
 "Question Order"=>"1",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Legal Cannabis Worldwide",
 "Question"=>
   "What North American country legalized cannabis for recreational purposes on October 17, 2018?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Canada",
 "Visible Characters"=>"2;5;6"},
{"Game"=>"7",
 "Game Name"=>"Ganja Glory",
 "Round Number"=>"1",
 "Question Order"=>"7",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Paraphernalia",
 "Question"=>
   "The power unit used to heat cannabis oil into an inhalable vapor.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Vape Pen",
 "Visible Characters"=>"1;5"},
{"Game"=>"7",
 "Game Name"=>"Ganja Glory",
 "Round Number"=>"3",
 "Question Order"=>"8",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Paraphernalia",
 "Question"=>
   "Widely popular in Europe, what is a joint that combines tobacco and cannabis.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Spliff",
 "Visible Characters"=>"5;6"},
{"Game"=>"1",
 "Game Name"=>"Basic Cannabis Trivia",
 "Round Number"=>"2",
 "Question Order"=>"10",
 "Difficulty"=>"1",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Strains",
 "Question"=>
   "These strains keep you up, give you energy and are best suited for running errands, hiking, and activities that require focus.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Sativa",
 "Visible Characters"=>"3;4;6"},
{"Game"=>"5",
 "Game Name"=>"Celebrities in Cannabis",
 "Round Number"=>"2",
 "Question Order"=>"10",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Cannabis Freedom Fighters",
 "Question"=>
   "The National Organization for the Reform of Marijuana Laws was founded in 1970 by who?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Keith Stroup",
 "Visible Characters"=>"2;4;8;11"},
{"Game"=>"3",
 "Game Name"=>"How Well Do You Know Cannabis?",
 "Round Number"=>"1",
 "Question Order"=>"2",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Celebrities in Cannabis",
 "Question"=>
   "Actor and activist for marijuana use, Tommy Chong also has a daughter who was in the movies \"Quest for Fire\", \"Commando\" with Arnold Schwarzenegger and \"The Color Purple\". Who is she?  ",
 "Number of Answers"=>"1",
 "Answer 1"=>"Rae Dawn Chong",
 "Visible Characters"=>"1;5;7;9;11;12"},
{"Game"=>"5",
 "Game Name"=>"Celebrities in Cannabis",
 "Round Number"=>"1",
 "Question Order"=>"5",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Celebrities in Cannabis",
 "Question"=>
   "In the 1998 movie, \"Half Baked\" what is the first name of Harland Williams character?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Kenny",
 "Visible Characters"=>"1;4;5"},
{"Game"=>"3",
 "Game Name"=>"How Well Do You Know Cannabis?",
 "Round Number"=>"5",
 "Question Order"=>"10",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Growing Cannabis",
 "Question"=>
   "What growing medium gives the experience of growing cannabis in soil, but have many of the same benefits as growing the plant hydroponically?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Coco coir",
 "Visible Characters"=>"1;4;5;8"},
{"Game"=>"4",
 "Game Name"=>"420 Know It All",
 "Round Number"=>"1",
 "Question Order"=>"5",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Legal Cannabis Worldwide",
 "Question"=>"What was the first country to legalize marijuana in 2013?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Uruguay",
 "Visible Characters"=>"1;4;6"},
{"Game"=>"4",
 "Game Name"=>"420 Know It All",
 "Round Number"=>"1",
 "Question Order"=>"6",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Lifestyle",
 "Question"=>
   "The ______ religion is famous for using cannabis as a sacred herb.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Rastafari",
 "Visible Characters"=>"1;3;7;9"},
{"Game"=>"4",
 "Game Name"=>"420 Know It All",
 "Round Number"=>"2",
 "Question Order"=>"6",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Medical Benefits",
 "Question"=>"One cognitive side effect of using cannabis is:",
 "Number of Answers"=>"1",
 "Answer 1"=>"Reaction time",
 "Visible Characters"=>"2;4;8;12"},
{"Game"=>"3",
 "Game Name"=>"How Well Do You Know Cannabis?",
 "Round Number"=>"2",
 "Question Order"=>"5",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Medical Benefits",
 "Question"=>"A cognitive side effect of using cannabis can be:",
 "Number of Answers"=>"1",
 "Answer 1"=>"Sensory perception",
 "Visible Characters"=>"1;4;10;15;17"},
{"Game"=>"3",
 "Game Name"=>"How Well Do You Know Cannabis?",
 "Round Number"=>"4",
 "Question Order"=>"2",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Methods of Consumption",
 "Question"=>
   "This is made by eliminating the plant material of marijuana and collecting the trichomes from the flower parts of the female cannabis plants.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Hashish",
 "Visible Characters"=>"4;5;7"},
{"Game"=>"4",
 "Game Name"=>"420 Know It All",
 "Round Number"=>"4",
 "Question Order"=>"3",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Paraphernalia",
 "Question"=>"A sacred Rastafari water pipe.",
 "Number of Answers"=>"1",
 "Answer 1"=>"Chalice",
 "Visible Characters"=>"2;3;6;7"},
{"Game"=>"3",
 "Game Name"=>"How Well Do You Know Cannabis?",
 "Round Number"=>"3",
 "Question Order"=>"9",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Politics",
 "Question"=>
   "What was the name of the document sent to all United States Attorneys and was formally titled \"Guidance Regarding Marijuana Enforcement\". It was issued in 2013 during the Obama administration and was rescinded by Attorney General Jeff Sessions in 2018.",
 "Number of Answers"=>"1",
 "Answer 1"=>"The Cole Memorandum",
 "Visible Characters"=>"1;4;6;9;"},
{"Game"=>"3",
 "Game Name"=>"How Well Do You Know Cannabis?",
 "Round Number"=>"4",
 "Question Order"=>"5",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Science of Cannabis",
 "Question"=>"What causes cannabis to be purple?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Anthocyanin",
 "Visible Characters"=>"3;6;7;8;11"},
{"Game"=>"8",
 "Game Name"=>"The Green Rush",
 "Round Number"=>"1",
 "Question Order"=>"6",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Strains",
 "Question"=>"This indica strain is also the name of a sweet treat",
 "Number of Answers"=>"1",
 "Answer 1"=>"Bubblegum",
 "Visible Characters"=>"3;4;9"},
{"Game"=>"3",
 "Game Name"=>"How Well Do You Know Cannabis?",
 "Round Number"=>"1",
 "Question Order"=>"8",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Strains",
 "Question"=>
   "Under what classification does the strain 98 Aloha White Widow fall under?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Hybrid",
 "Visible Characters"=>"2;5;6"},
{"Game"=>"4",
 "Game Name"=>"420 Know It All",
 "Round Number"=>"5",
 "Question Order"=>"3",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Strains",
 "Question"=>"Under what classification does the strain 13 Dawgs fall under?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Hybrid",
 "Visible Characters"=>"1;3;6"},
{"Game"=>"4",
 "Game Name"=>"420 Know It All",
 "Round Number"=>"2",
 "Question Order"=>"7",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Strains",
 "Question"=>"24k Gold is a cross between Kosher Kush and what other strain?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Tangie",
 "Visible Characters"=>"1;6"},
{"Game"=>"3",
 "Game Name"=>"How Well Do You Know Cannabis?",
 "Round Number"=>"3",
 "Question Order"=>"1",
 "Difficulty"=>"2",
 "Question Type"=>"Fill in the Blank",
 "Topic"=>"Strains",
 "Question"=>
   "The strain 3 Kings was named after it's unique genetics which include Sour Diesel, OG Kush and what other noteably popular cannabis strain?",
 "Number of Answers"=>"1",
 "Answer 1"=>"Headband",
 "Visible Characters"=>"1;2;6;8"}
]


def obfuscate(answer, chars = nil)
  hidden = "_" * answer.size
  unless chars.nil?
    chars = chars.split(";")
    chars.each do |value|
      real_index = value.to_i-1;
      hidden[real_index] = answer[real_index]
    end
  end
  hidden
end

rows.each do |row|
  question = Trivia::HangmanAvailableQuestion.new(
    title: row["Question"],
    cooldown_period: 10,
    time_limit: 5,
    status: :published,
    complexity: row["Difficulty"]
  )

  question.topic = Trivia::Topic.where(name: row["Topic"]).first
  question.save!
  question.available_answers.create(
    name: obfuscate(row["Answer 1"], row["Visible Characters"]),
    hint: row["Answer 1"],
    is_correct: true,
    status: :published
  )
end
