json.id activity.id.to_s
json.quest_id activity.quest_id.to_s
json.description activity.description
json.hint activity.hint
json.post activity.post
json.image activity.image
json.audio activity.audio
json.beacon activity.beacon
json.activity_code activity.activity_code.to_s
json.step activity.step.to_s